"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import google.protobuf.descriptor as _google_protobuf_descriptor
import google.protobuf.message as _google_protobuf_message
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    import typing as _typing_extensions
else:
    import typing_extensions as _typing_extensions

DESCRIPTOR: _google_protobuf_descriptor.FileDescriptor

@_typing.final
class TestMessage(_google_protobuf_message.Message):
    DESCRIPTOR: _google_protobuf_descriptor.Descriptor

    FOO_FIELD_NUMBER: _builtins.int
    foo: _builtins.str
    def __init__(
        self,
        *,
        foo: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _typing_extensions.TypeAlias = _typing.Literal["foo", b"foo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TestMessage: _typing_extensions.TypeAlias = TestMessage  # noqa: Y015
