"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from testproto import test3_pb2 as _test3_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Inner(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    a: _test3_pb2.OuterEnum.ValueType
    def __init__(
        self,
        *,
        a: _test3_pb2.OuterEnum.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Inner: _TypeAlias = Inner  # noqa: Y015
