"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Proto 3 test file."""

from collections import abc as _abc
from testproto.grpc import deprecated_pb2 as _deprecated_pb2
import abc as _abc_1
import builtins as _builtins
import grpc as _grpc
import sys

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated


GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

@_deprecated("""This stub is within a file that has been marked as deprecated using proto file options.""")
class DeprecatedFileNonDeprecatedServiceStub:
    def __init__(self, channel: _grpc.Channel) -> None: ...
    @_builtins.property
    @_deprecated("""This method is within a file that has been marked as deprecated using proto file options.""")
    def DeprecatedFileNonDeprecatedMethod(self) -> _grpc.UnaryUnaryMultiCallable[_deprecated_pb2.DeprecatedFileNonDeprecatedMessage, _deprecated_pb2.DeprecatedFileNonDeprecatedMessage]: ...

@_deprecated("""This servicer is within a file that has been marked as deprecated using proto file options.""")
class DeprecatedFileNonDeprecatedServiceServicer(metaclass=_abc_1.ABCMeta):
    @_deprecated("""This method is within a file that has been marked as deprecated using proto file options.""")
    @_abc_1.abstractmethod
    def DeprecatedFileNonDeprecatedMethod(
        self,
        request: _deprecated_pb2.DeprecatedFileNonDeprecatedMessage,
        context: _grpc.ServicerContext,
    ) -> _deprecated_pb2.DeprecatedFileNonDeprecatedMessage: ...

@_deprecated("""This servicer is within a file that has been marked as deprecated using proto file options.""")
def add_DeprecatedFileNonDeprecatedServiceServicer_to_server(servicer: DeprecatedFileNonDeprecatedServiceServicer, server: _grpc.Server) -> None: ...

@_deprecated("""This service is deprecated""")
class DeprecatedFileDeprecatedServiceStub:
    def __init__(self, channel: _grpc.Channel) -> None: ...
    @_builtins.property
    @_deprecated("""This method is deprecated""")
    def DeprecatedFileDeprecatedMethod(self) -> _grpc.UnaryUnaryMultiCallable[_deprecated_pb2.DeprecatedFileDeprecatedMessage, _deprecated_pb2.DeprecatedFileDeprecatedMessage]: ...

@_deprecated("""This service is deprecated""")
class DeprecatedFileDeprecatedServiceServicer(metaclass=_abc_1.ABCMeta):
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    @_abc_1.abstractmethod
    def DeprecatedFileDeprecatedMethod(
        self,
        request: _deprecated_pb2.DeprecatedFileDeprecatedMessage,
        context: _grpc.ServicerContext,
    ) -> _deprecated_pb2.DeprecatedFileDeprecatedMessage: ...

@_deprecated("""This service is deprecated""")
def add_DeprecatedFileDeprecatedServiceServicer_to_server(servicer: DeprecatedFileDeprecatedServiceServicer, server: _grpc.Server) -> None: ...
