# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testproto/grpc/dummy.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'testproto/grpc/dummy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atestproto/grpc/dummy.proto\x12\x05\x64ummy\"\x1d\n\x0c\x44ummyRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nDummyReply\x12\r\n\x05value\x18\x01 \x01(\t\".\n\x11\x44\x65precatedRequest\x12\x15\n\told_field\x18\x01 \x01(\tB\x02\x18\x01:\x02\x18\x01\x32\xfa\x01\n\x0c\x44ummyService\x12\x36\n\nUnaryUnary\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00\x12\x39\n\x0bUnaryStream\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00\x30\x01\x12\x39\n\x0bStreamUnary\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00(\x01\x12<\n\x0cStreamStream\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00(\x01\x30\x01\x32\xb3\x01\n\x11\x44\x65precatedService\x12\x44\n\x10\x44\x65precatedMethod\x12\x18.dummy.DeprecatedRequest\x1a\x11.dummy.DummyReply\"\x03\x88\x02\x01\x12S\n$DeprecatedMethodNotDeprecatedRequest\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x03\x88\x02\x01\x1a\x03\x88\x02\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testproto.grpc.dummy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPRECATEDREQUEST'].fields_by_name['old_field']._loaded_options = None
  _globals['_DEPRECATEDREQUEST'].fields_by_name['old_field']._serialized_options = b'\030\001'
  _globals['_DEPRECATEDREQUEST']._loaded_options = None
  _globals['_DEPRECATEDREQUEST']._serialized_options = b'\030\001'
  _globals['_DEPRECATEDSERVICE']._loaded_options = None
  _globals['_DEPRECATEDSERVICE']._serialized_options = b'\210\002\001'
  _globals['_DEPRECATEDSERVICE'].methods_by_name['DeprecatedMethod']._loaded_options = None
  _globals['_DEPRECATEDSERVICE'].methods_by_name['DeprecatedMethod']._serialized_options = b'\210\002\001'
  _globals['_DEPRECATEDSERVICE'].methods_by_name['DeprecatedMethodNotDeprecatedRequest']._loaded_options = None
  _globals['_DEPRECATEDSERVICE'].methods_by_name['DeprecatedMethodNotDeprecatedRequest']._serialized_options = b'\210\002\001'
  _globals['_DUMMYREQUEST']._serialized_start=37
  _globals['_DUMMYREQUEST']._serialized_end=66
  _globals['_DUMMYREPLY']._serialized_start=68
  _globals['_DUMMYREPLY']._serialized_end=95
  _globals['_DEPRECATEDREQUEST']._serialized_start=97
  _globals['_DEPRECATEDREQUEST']._serialized_end=143
  _globals['_DUMMYSERVICE']._serialized_start=146
  _globals['_DUMMYSERVICE']._serialized_end=396
  _globals['_DEPRECATEDSERVICE']._serialized_start=399
  _globals['_DEPRECATEDSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
