"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import google.protobuf.descriptor as _google_protobuf_descriptor
import google.protobuf.message as _google_protobuf_message
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    import typing as _typing_extensions
else:
    import typing_extensions as _typing_extensions

DESCRIPTOR: _google_protobuf_descriptor.FileDescriptor

@_typing.final
class Test(_google_protobuf_message.Message):
    DESCRIPTOR: _google_protobuf_descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    C_FIELD_NUMBER: _builtins.int
    D_FIELD_NUMBER: _builtins.int
    E_FIELD_NUMBER: _builtins.int
    F_FIELD_NUMBER: _builtins.int
    G_FIELD_NUMBER: _builtins.int
    H_FIELD_NUMBER: _builtins.int
    I_FIELD_NUMBER: _builtins.int
    J_FIELD_NUMBER: _builtins.int
    K_FIELD_NUMBER: _builtins.int
    a: _builtins.str
    """Ending with " """
    b: _builtins.str
    """Ending with "" """
    c: _builtins.str
    """Ending with \"\"\" """
    d: _builtins.str
    """Ending with \\ """
    e: _builtins.str
    """Containing bad escape: \\x"""
    f: _builtins.str
    """Containing \"\"\"" quadruple"""
    g: _builtins.str
    """Containing \"\"\""" quintuple"""
    h: _builtins.str
    """Containing \"\"\"\"\"\" sextuple"""
    i: _builtins.str
    """\"\"\" Multiple \"\"\" triples \"\"\" """
    j: _builtins.str
    """"quotes" can be a problem in comments.
    \"\"\"Triple quotes\"\"\" just as well
    """
    k: _builtins.str
    """\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"
    "                                              "
    " Super Duper comments with surrounding edges! "
    "                                              "
    "            Pay attention to me!!!!           "
    "                                              "
    \"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"
    """
    def __init__(
        self,
        *,
        a: _builtins.str = ...,
        b: _builtins.str = ...,
        c: _builtins.str = ...,
        d: _builtins.str = ...,
        e: _builtins.str = ...,
        f: _builtins.str = ...,
        g: _builtins.str = ...,
        h: _builtins.str = ...,
        i: _builtins.str = ...,
        j: _builtins.str = ...,
        k: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _typing_extensions.TypeAlias = _typing.Literal["a", b"a", "b", b"b", "c", b"c", "d", b"d", "e", b"e", "f", b"f", "g", b"g", "h", b"h", "i", b"i", "j", b"j", "k", b"k"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Test: _typing_extensions.TypeAlias = Test  # noqa: Y015
