"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Edition version of proto2 file"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Editions2024SubMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    THING_FIELD_NUMBER: builtins.int
    thing: builtins.str
    def __init__(
        self,
        *,
        thing: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["thing", b"thing"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["thing", b"thing"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Editions2024SubMessage: typing_extensions.TypeAlias = Editions2024SubMessage

@typing.final
class Editions2024Test(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEGACY_FIELD_NUMBER: builtins.int
    EXPLICIT_SINGULAR_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_FIELD_NUMBER: builtins.int
    IMPLICIT_SINGULAR_FIELD_NUMBER: builtins.int
    DEFAULT_SINGULAR_FIELD_NUMBER: builtins.int
    legacy: builtins.str
    """Expect to be always set"""
    explicit_singular: builtins.str
    """Expect HasField generated"""
    implicit_singular: builtins.str
    """Expect implicit field presence, no HasField generated"""
    default_singular: builtins.str
    """Not set, should default to EXPLICIT"""
    @property
    def message_field(self) -> Global___Editions2024SubMessage:
        """Expect HasField generated?"""

    def __init__(
        self,
        *,
        legacy: builtins.str | None = ...,
        explicit_singular: builtins.str | None = ...,
        message_field: Global___Editions2024SubMessage | None = ...,
        implicit_singular: builtins.str = ...,
        default_singular: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["default_singular", b"default_singular", "explicit_singular", b"explicit_singular", "legacy", b"legacy", "message_field", b"message_field"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["default_singular", b"default_singular", "explicit_singular", b"explicit_singular", "implicit_singular", b"implicit_singular", "legacy", b"legacy", "message_field", b"message_field"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Editions2024Test: typing_extensions.TypeAlias = Editions2024Test
