"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Proto 2 test file."""

from collections import abc as _abc
from grpc import aio as _aio
from testproto import test_pb2 as _test_pb2
import abc as _abc_1


GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PythonReservedKeywordsServiceStub:
    """Method name is reserved"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    valid_method_name1: _aio.UnaryUnaryMultiCallable[_test_pb2.Simple1, _test_pb2._r_None]
    """valid_method_name1"""
    valid_method_name2: _aio.UnaryUnaryMultiCallable[_test_pb2.Simple1, _test_pb2.PythonReservedKeywords._r_lambda]
    """valid_method_name2"""

class PythonReservedKeywordsServiceServicer(metaclass=_abc_1.ABCMeta):
    """Method name is reserved"""

    @_abc_1.abstractmethod
    def valid_method_name1(
        self,
        request: _test_pb2.Simple1,
        context: _aio.ServicerContext[_test_pb2.Simple1, _abc.Awaitable[_test_pb2._r_None]],
    ) -> _abc.Awaitable[_test_pb2._r_None]:
        """valid_method_name1"""

    @_abc_1.abstractmethod
    def valid_method_name2(
        self,
        request: _test_pb2.Simple1,
        context: _aio.ServicerContext[_test_pb2.Simple1, _abc.Awaitable[_test_pb2.PythonReservedKeywords._r_lambda]],
    ) -> _abc.Awaitable[_test_pb2.PythonReservedKeywords._r_lambda]:
        """valid_method_name2"""

def add_PythonReservedKeywordsServiceServicer_to_server(servicer: PythonReservedKeywordsServiceServicer, server: _aio.Server) -> None: ...
