"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
https://github.com/vmagamedov/grpclib/blob/master/tests/dummy.proto"""

from collections import abc as _abc
from grpc import aio as _aio
from testproto.grpc import dummy_pb2 as _dummy_pb2
import abc as _abc_1
import builtins as _builtins
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DummyServiceStub:
    """DummyService"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DummyServiceAsyncStub: ...
    UnaryUnary: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]
    """UnaryUnary"""
    UnaryStream: _grpc.UnaryStreamMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]
    """UnaryStream"""
    StreamUnary: _grpc.StreamUnaryMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]
    """StreamUnary"""
    StreamStream: _grpc.StreamStreamMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]
    """StreamStream"""

@_typing.type_check_only
class DummyServiceAsyncStub(DummyServiceStub):
    """DummyService"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    UnaryUnary: _aio.UnaryUnaryMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]  # type: ignore[assignment]
    """UnaryUnary"""
    UnaryStream: _aio.UnaryStreamMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]  # type: ignore[assignment]
    """UnaryStream"""
    StreamUnary: _aio.StreamUnaryMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]  # type: ignore[assignment]
    """StreamUnary"""
    StreamStream: _aio.StreamStreamMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]  # type: ignore[assignment]
    """StreamStream"""

class DummyServiceServicer:
    """DummyService"""

    def UnaryUnary(
        self,
        request: _dummy_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.DummyReply, _abc.Awaitable[_dummy_pb2.DummyReply]]:
        """UnaryUnary"""

    def UnaryStream(
        self,
        request: _dummy_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_dummy_pb2.DummyReply], _abc.AsyncIterator[_dummy_pb2.DummyReply]]:
        """UnaryStream"""

    def StreamUnary(
        self,
        request_iterator: _MaybeAsyncIterator[_dummy_pb2.DummyRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.DummyReply, _abc.Awaitable[_dummy_pb2.DummyReply]]:
        """StreamUnary"""

    def StreamStream(
        self,
        request_iterator: _MaybeAsyncIterator[_dummy_pb2.DummyRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_dummy_pb2.DummyReply], _abc.AsyncIterator[_dummy_pb2.DummyReply]]:
        """StreamStream"""

def add_DummyServiceServicer_to_server(servicer: DummyServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

@_deprecated("""This service is deprecated""")
class DeprecatedServiceStub:
    """Marking the service as deprecated"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DeprecatedServiceAsyncStub: ...
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def DeprecatedMethod(self) -> _grpc.UnaryUnaryMultiCallable[_dummy_pb2.DeprecatedRequest, _dummy_pb2.DummyReply]:
        """DeprecatedMethod"""
    @_builtins.property
    @_deprecated("""Method is deprecated, but request message is not""")
    def DeprecatedMethodNotDeprecatedRequest(self) -> _grpc.UnaryUnaryMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]:
        """DeprecatedMethodNotDeprecatedRequest"""
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def DeprecatedMethodNoComments(self) -> _grpc.UnaryUnaryMultiCallable[_dummy_pb2.DeprecatedRequest, _dummy_pb2.DummyReply]: ...

@_deprecated("""This service is deprecated""")
@_typing.type_check_only
class DeprecatedServiceAsyncStub(DeprecatedServiceStub):
    """Marking the service as deprecated"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def DeprecatedMethod(self) -> _aio.UnaryUnaryMultiCallable[_dummy_pb2.DeprecatedRequest, _dummy_pb2.DummyReply]:  # type: ignore[override]
        """DeprecatedMethod"""
    @_builtins.property
    @_deprecated("""Method is deprecated, but request message is not""")
    def DeprecatedMethodNotDeprecatedRequest(self) -> _aio.UnaryUnaryMultiCallable[_dummy_pb2.DummyRequest, _dummy_pb2.DummyReply]:  # type: ignore[override]
        """DeprecatedMethodNotDeprecatedRequest"""
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def DeprecatedMethodNoComments(self) -> _aio.UnaryUnaryMultiCallable[_dummy_pb2.DeprecatedRequest, _dummy_pb2.DummyReply]: ...  # type: ignore[override]

@_deprecated("""This service is deprecated""")
class DeprecatedServiceServicer:
    """Marking the service as deprecated"""

    @_deprecated("""DeprecatedMethod""")
    def DeprecatedMethod(
        self,
        request: _dummy_pb2.DeprecatedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.DummyReply, _abc.Awaitable[_dummy_pb2.DummyReply]]:
        """DeprecatedMethod"""

    @_deprecated("""DeprecatedMethodNotDeprecatedRequest""")
    def DeprecatedMethodNotDeprecatedRequest(
        self,
        request: _dummy_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.DummyReply, _abc.Awaitable[_dummy_pb2.DummyReply]]:
        """DeprecatedMethodNotDeprecatedRequest"""

    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def DeprecatedMethodNoComments(
        self,
        request: _dummy_pb2.DeprecatedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.DummyReply, _abc.Awaitable[_dummy_pb2.DummyReply]]: ...

@_deprecated("""This service is deprecated""")
def add_DeprecatedServiceServicer_to_server(servicer: DeprecatedServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class ManyRPCsServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ManyRPCsServiceAsyncStub: ...
    Method1: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest1, _dummy_pb2.ManyResponse1]
    Method2: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest2, _dummy_pb2.ManyResponse2]
    Method3: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest3, _dummy_pb2.ManyResponse3]
    Method4: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest4, _dummy_pb2.ManyResponse4]
    Method5: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest5, _dummy_pb2.ManyResponse5]
    Method6: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest6, _dummy_pb2.ManyResponse6]
    Method7: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest7, _dummy_pb2.ManyResponse7]
    Method8: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest8, _dummy_pb2.ManyResponse8]
    Method9: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest9, _dummy_pb2.ManyResponse9]
    Method10: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest10, _dummy_pb2.ManyResponse10]
    Method11: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest11, _dummy_pb2.ManyResponse11]
    Method12: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest12, _dummy_pb2.ManyResponse12]
    Method13: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest13, _dummy_pb2.ManyResponse13]
    Method14: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest14, _dummy_pb2.ManyResponse14]
    Method15: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest15, _dummy_pb2.ManyResponse15]
    Method16: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest16, _dummy_pb2.ManyResponse16]
    Method17: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest17, _dummy_pb2.ManyResponse17]
    Method18: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest18, _dummy_pb2.ManyResponse18]
    Method19: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest19, _dummy_pb2.ManyResponse19]
    Method20: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest20, _dummy_pb2.ManyResponse20]
    Method21: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest21, _dummy_pb2.ManyResponse21]
    Method22: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest22, _dummy_pb2.ManyResponse22]
    Method23: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest23, _dummy_pb2.ManyResponse23]
    Method24: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest24, _dummy_pb2.ManyResponse24]
    Method25: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest25, _dummy_pb2.ManyResponse25]
    Method26: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest26, _dummy_pb2.ManyResponse26]
    Method27: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest27, _dummy_pb2.ManyResponse27]
    Method28: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest28, _dummy_pb2.ManyResponse28]
    Method29: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest29, _dummy_pb2.ManyResponse29]
    Method30: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest30, _dummy_pb2.ManyResponse30]
    Method31: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest31, _dummy_pb2.ManyResponse31]
    Method32: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest32, _dummy_pb2.ManyResponse32]
    Method33: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest33, _dummy_pb2.ManyResponse33]
    Method34: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest34, _dummy_pb2.ManyResponse34]
    Method35: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest35, _dummy_pb2.ManyResponse35]
    Method36: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest36, _dummy_pb2.ManyResponse36]
    Method37: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest37, _dummy_pb2.ManyResponse37]
    Method38: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest38, _dummy_pb2.ManyResponse38]
    Method39: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest39, _dummy_pb2.ManyResponse39]
    Method40: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest40, _dummy_pb2.ManyResponse40]
    Method41: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest41, _dummy_pb2.ManyResponse41]
    Method42: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest42, _dummy_pb2.ManyResponse42]
    Method43: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest43, _dummy_pb2.ManyResponse43]
    Method44: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest44, _dummy_pb2.ManyResponse44]
    Method45: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest45, _dummy_pb2.ManyResponse45]
    Method46: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest46, _dummy_pb2.ManyResponse46]
    Method47: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest47, _dummy_pb2.ManyResponse47]
    Method48: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest48, _dummy_pb2.ManyResponse48]
    Method49: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest49, _dummy_pb2.ManyResponse49]
    Method50: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest50, _dummy_pb2.ManyResponse50]
    Method51: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest51, _dummy_pb2.ManyResponse51]
    Method52: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest52, _dummy_pb2.ManyResponse52]
    Method53: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest53, _dummy_pb2.ManyResponse53]
    Method54: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest54, _dummy_pb2.ManyResponse54]
    Method55: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest55, _dummy_pb2.ManyResponse55]
    Method56: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest56, _dummy_pb2.ManyResponse56]
    Method57: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest57, _dummy_pb2.ManyResponse57]
    Method58: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest58, _dummy_pb2.ManyResponse58]
    Method59: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest59, _dummy_pb2.ManyResponse59]
    Method60: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest60, _dummy_pb2.ManyResponse60]
    Method61: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest61, _dummy_pb2.ManyResponse61]
    Method62: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest62, _dummy_pb2.ManyResponse62]
    Method63: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest63, _dummy_pb2.ManyResponse63]
    Method64: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest64, _dummy_pb2.ManyResponse64]
    Method65: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest65, _dummy_pb2.ManyResponse65]
    Method66: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest66, _dummy_pb2.ManyResponse66]
    Method67: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest67, _dummy_pb2.ManyResponse67]
    Method68: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest68, _dummy_pb2.ManyResponse68]
    Method69: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest69, _dummy_pb2.ManyResponse69]
    Method70: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest70, _dummy_pb2.ManyResponse70]
    Method71: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest71, _dummy_pb2.ManyResponse71]
    Method72: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest72, _dummy_pb2.ManyResponse72]
    Method73: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest73, _dummy_pb2.ManyResponse73]
    Method74: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest74, _dummy_pb2.ManyResponse74]
    Method75: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest75, _dummy_pb2.ManyResponse75]
    Method76: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest76, _dummy_pb2.ManyResponse76]
    Method77: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest77, _dummy_pb2.ManyResponse77]
    Method78: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest78, _dummy_pb2.ManyResponse78]
    Method79: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest79, _dummy_pb2.ManyResponse79]
    Method80: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest80, _dummy_pb2.ManyResponse80]
    Method81: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest81, _dummy_pb2.ManyResponse81]
    Method82: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest82, _dummy_pb2.ManyResponse82]
    Method83: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest83, _dummy_pb2.ManyResponse83]
    Method84: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest84, _dummy_pb2.ManyResponse84]
    Method85: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest85, _dummy_pb2.ManyResponse85]
    Method86: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest86, _dummy_pb2.ManyResponse86]
    Method87: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest87, _dummy_pb2.ManyResponse87]
    Method88: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest88, _dummy_pb2.ManyResponse88]
    Method89: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest89, _dummy_pb2.ManyResponse89]
    Method90: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest90, _dummy_pb2.ManyResponse90]
    Method91: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest91, _dummy_pb2.ManyResponse91]
    Method92: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest92, _dummy_pb2.ManyResponse92]
    Method93: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest93, _dummy_pb2.ManyResponse93]
    Method94: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest94, _dummy_pb2.ManyResponse94]
    Method95: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest95, _dummy_pb2.ManyResponse95]
    Method96: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest96, _dummy_pb2.ManyResponse96]
    Method97: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest97, _dummy_pb2.ManyResponse97]
    Method98: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest98, _dummy_pb2.ManyResponse98]
    Method99: _grpc.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest99, _dummy_pb2.ManyResponse99]

@_typing.type_check_only
class ManyRPCsServiceAsyncStub(ManyRPCsServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Method1: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest1, _dummy_pb2.ManyResponse1]  # type: ignore[assignment]
    Method2: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest2, _dummy_pb2.ManyResponse2]  # type: ignore[assignment]
    Method3: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest3, _dummy_pb2.ManyResponse3]  # type: ignore[assignment]
    Method4: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest4, _dummy_pb2.ManyResponse4]  # type: ignore[assignment]
    Method5: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest5, _dummy_pb2.ManyResponse5]  # type: ignore[assignment]
    Method6: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest6, _dummy_pb2.ManyResponse6]  # type: ignore[assignment]
    Method7: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest7, _dummy_pb2.ManyResponse7]  # type: ignore[assignment]
    Method8: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest8, _dummy_pb2.ManyResponse8]  # type: ignore[assignment]
    Method9: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest9, _dummy_pb2.ManyResponse9]  # type: ignore[assignment]
    Method10: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest10, _dummy_pb2.ManyResponse10]  # type: ignore[assignment]
    Method11: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest11, _dummy_pb2.ManyResponse11]  # type: ignore[assignment]
    Method12: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest12, _dummy_pb2.ManyResponse12]  # type: ignore[assignment]
    Method13: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest13, _dummy_pb2.ManyResponse13]  # type: ignore[assignment]
    Method14: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest14, _dummy_pb2.ManyResponse14]  # type: ignore[assignment]
    Method15: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest15, _dummy_pb2.ManyResponse15]  # type: ignore[assignment]
    Method16: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest16, _dummy_pb2.ManyResponse16]  # type: ignore[assignment]
    Method17: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest17, _dummy_pb2.ManyResponse17]  # type: ignore[assignment]
    Method18: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest18, _dummy_pb2.ManyResponse18]  # type: ignore[assignment]
    Method19: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest19, _dummy_pb2.ManyResponse19]  # type: ignore[assignment]
    Method20: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest20, _dummy_pb2.ManyResponse20]  # type: ignore[assignment]
    Method21: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest21, _dummy_pb2.ManyResponse21]  # type: ignore[assignment]
    Method22: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest22, _dummy_pb2.ManyResponse22]  # type: ignore[assignment]
    Method23: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest23, _dummy_pb2.ManyResponse23]  # type: ignore[assignment]
    Method24: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest24, _dummy_pb2.ManyResponse24]  # type: ignore[assignment]
    Method25: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest25, _dummy_pb2.ManyResponse25]  # type: ignore[assignment]
    Method26: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest26, _dummy_pb2.ManyResponse26]  # type: ignore[assignment]
    Method27: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest27, _dummy_pb2.ManyResponse27]  # type: ignore[assignment]
    Method28: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest28, _dummy_pb2.ManyResponse28]  # type: ignore[assignment]
    Method29: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest29, _dummy_pb2.ManyResponse29]  # type: ignore[assignment]
    Method30: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest30, _dummy_pb2.ManyResponse30]  # type: ignore[assignment]
    Method31: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest31, _dummy_pb2.ManyResponse31]  # type: ignore[assignment]
    Method32: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest32, _dummy_pb2.ManyResponse32]  # type: ignore[assignment]
    Method33: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest33, _dummy_pb2.ManyResponse33]  # type: ignore[assignment]
    Method34: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest34, _dummy_pb2.ManyResponse34]  # type: ignore[assignment]
    Method35: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest35, _dummy_pb2.ManyResponse35]  # type: ignore[assignment]
    Method36: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest36, _dummy_pb2.ManyResponse36]  # type: ignore[assignment]
    Method37: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest37, _dummy_pb2.ManyResponse37]  # type: ignore[assignment]
    Method38: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest38, _dummy_pb2.ManyResponse38]  # type: ignore[assignment]
    Method39: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest39, _dummy_pb2.ManyResponse39]  # type: ignore[assignment]
    Method40: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest40, _dummy_pb2.ManyResponse40]  # type: ignore[assignment]
    Method41: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest41, _dummy_pb2.ManyResponse41]  # type: ignore[assignment]
    Method42: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest42, _dummy_pb2.ManyResponse42]  # type: ignore[assignment]
    Method43: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest43, _dummy_pb2.ManyResponse43]  # type: ignore[assignment]
    Method44: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest44, _dummy_pb2.ManyResponse44]  # type: ignore[assignment]
    Method45: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest45, _dummy_pb2.ManyResponse45]  # type: ignore[assignment]
    Method46: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest46, _dummy_pb2.ManyResponse46]  # type: ignore[assignment]
    Method47: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest47, _dummy_pb2.ManyResponse47]  # type: ignore[assignment]
    Method48: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest48, _dummy_pb2.ManyResponse48]  # type: ignore[assignment]
    Method49: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest49, _dummy_pb2.ManyResponse49]  # type: ignore[assignment]
    Method50: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest50, _dummy_pb2.ManyResponse50]  # type: ignore[assignment]
    Method51: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest51, _dummy_pb2.ManyResponse51]  # type: ignore[assignment]
    Method52: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest52, _dummy_pb2.ManyResponse52]  # type: ignore[assignment]
    Method53: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest53, _dummy_pb2.ManyResponse53]  # type: ignore[assignment]
    Method54: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest54, _dummy_pb2.ManyResponse54]  # type: ignore[assignment]
    Method55: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest55, _dummy_pb2.ManyResponse55]  # type: ignore[assignment]
    Method56: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest56, _dummy_pb2.ManyResponse56]  # type: ignore[assignment]
    Method57: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest57, _dummy_pb2.ManyResponse57]  # type: ignore[assignment]
    Method58: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest58, _dummy_pb2.ManyResponse58]  # type: ignore[assignment]
    Method59: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest59, _dummy_pb2.ManyResponse59]  # type: ignore[assignment]
    Method60: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest60, _dummy_pb2.ManyResponse60]  # type: ignore[assignment]
    Method61: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest61, _dummy_pb2.ManyResponse61]  # type: ignore[assignment]
    Method62: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest62, _dummy_pb2.ManyResponse62]  # type: ignore[assignment]
    Method63: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest63, _dummy_pb2.ManyResponse63]  # type: ignore[assignment]
    Method64: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest64, _dummy_pb2.ManyResponse64]  # type: ignore[assignment]
    Method65: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest65, _dummy_pb2.ManyResponse65]  # type: ignore[assignment]
    Method66: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest66, _dummy_pb2.ManyResponse66]  # type: ignore[assignment]
    Method67: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest67, _dummy_pb2.ManyResponse67]  # type: ignore[assignment]
    Method68: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest68, _dummy_pb2.ManyResponse68]  # type: ignore[assignment]
    Method69: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest69, _dummy_pb2.ManyResponse69]  # type: ignore[assignment]
    Method70: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest70, _dummy_pb2.ManyResponse70]  # type: ignore[assignment]
    Method71: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest71, _dummy_pb2.ManyResponse71]  # type: ignore[assignment]
    Method72: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest72, _dummy_pb2.ManyResponse72]  # type: ignore[assignment]
    Method73: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest73, _dummy_pb2.ManyResponse73]  # type: ignore[assignment]
    Method74: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest74, _dummy_pb2.ManyResponse74]  # type: ignore[assignment]
    Method75: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest75, _dummy_pb2.ManyResponse75]  # type: ignore[assignment]
    Method76: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest76, _dummy_pb2.ManyResponse76]  # type: ignore[assignment]
    Method77: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest77, _dummy_pb2.ManyResponse77]  # type: ignore[assignment]
    Method78: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest78, _dummy_pb2.ManyResponse78]  # type: ignore[assignment]
    Method79: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest79, _dummy_pb2.ManyResponse79]  # type: ignore[assignment]
    Method80: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest80, _dummy_pb2.ManyResponse80]  # type: ignore[assignment]
    Method81: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest81, _dummy_pb2.ManyResponse81]  # type: ignore[assignment]
    Method82: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest82, _dummy_pb2.ManyResponse82]  # type: ignore[assignment]
    Method83: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest83, _dummy_pb2.ManyResponse83]  # type: ignore[assignment]
    Method84: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest84, _dummy_pb2.ManyResponse84]  # type: ignore[assignment]
    Method85: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest85, _dummy_pb2.ManyResponse85]  # type: ignore[assignment]
    Method86: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest86, _dummy_pb2.ManyResponse86]  # type: ignore[assignment]
    Method87: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest87, _dummy_pb2.ManyResponse87]  # type: ignore[assignment]
    Method88: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest88, _dummy_pb2.ManyResponse88]  # type: ignore[assignment]
    Method89: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest89, _dummy_pb2.ManyResponse89]  # type: ignore[assignment]
    Method90: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest90, _dummy_pb2.ManyResponse90]  # type: ignore[assignment]
    Method91: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest91, _dummy_pb2.ManyResponse91]  # type: ignore[assignment]
    Method92: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest92, _dummy_pb2.ManyResponse92]  # type: ignore[assignment]
    Method93: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest93, _dummy_pb2.ManyResponse93]  # type: ignore[assignment]
    Method94: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest94, _dummy_pb2.ManyResponse94]  # type: ignore[assignment]
    Method95: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest95, _dummy_pb2.ManyResponse95]  # type: ignore[assignment]
    Method96: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest96, _dummy_pb2.ManyResponse96]  # type: ignore[assignment]
    Method97: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest97, _dummy_pb2.ManyResponse97]  # type: ignore[assignment]
    Method98: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest98, _dummy_pb2.ManyResponse98]  # type: ignore[assignment]
    Method99: _aio.UnaryUnaryMultiCallable[_dummy_pb2.ManyRequest99, _dummy_pb2.ManyResponse99]  # type: ignore[assignment]

class ManyRPCsServiceServicer:
    def Method1(
        self,
        request: _dummy_pb2.ManyRequest1,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse1, _abc.Awaitable[_dummy_pb2.ManyResponse1]]: ...

    def Method2(
        self,
        request: _dummy_pb2.ManyRequest2,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse2, _abc.Awaitable[_dummy_pb2.ManyResponse2]]: ...

    def Method3(
        self,
        request: _dummy_pb2.ManyRequest3,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse3, _abc.Awaitable[_dummy_pb2.ManyResponse3]]: ...

    def Method4(
        self,
        request: _dummy_pb2.ManyRequest4,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse4, _abc.Awaitable[_dummy_pb2.ManyResponse4]]: ...

    def Method5(
        self,
        request: _dummy_pb2.ManyRequest5,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse5, _abc.Awaitable[_dummy_pb2.ManyResponse5]]: ...

    def Method6(
        self,
        request: _dummy_pb2.ManyRequest6,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse6, _abc.Awaitable[_dummy_pb2.ManyResponse6]]: ...

    def Method7(
        self,
        request: _dummy_pb2.ManyRequest7,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse7, _abc.Awaitable[_dummy_pb2.ManyResponse7]]: ...

    def Method8(
        self,
        request: _dummy_pb2.ManyRequest8,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse8, _abc.Awaitable[_dummy_pb2.ManyResponse8]]: ...

    def Method9(
        self,
        request: _dummy_pb2.ManyRequest9,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse9, _abc.Awaitable[_dummy_pb2.ManyResponse9]]: ...

    def Method10(
        self,
        request: _dummy_pb2.ManyRequest10,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse10, _abc.Awaitable[_dummy_pb2.ManyResponse10]]: ...

    def Method11(
        self,
        request: _dummy_pb2.ManyRequest11,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse11, _abc.Awaitable[_dummy_pb2.ManyResponse11]]: ...

    def Method12(
        self,
        request: _dummy_pb2.ManyRequest12,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse12, _abc.Awaitable[_dummy_pb2.ManyResponse12]]: ...

    def Method13(
        self,
        request: _dummy_pb2.ManyRequest13,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse13, _abc.Awaitable[_dummy_pb2.ManyResponse13]]: ...

    def Method14(
        self,
        request: _dummy_pb2.ManyRequest14,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse14, _abc.Awaitable[_dummy_pb2.ManyResponse14]]: ...

    def Method15(
        self,
        request: _dummy_pb2.ManyRequest15,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse15, _abc.Awaitable[_dummy_pb2.ManyResponse15]]: ...

    def Method16(
        self,
        request: _dummy_pb2.ManyRequest16,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse16, _abc.Awaitable[_dummy_pb2.ManyResponse16]]: ...

    def Method17(
        self,
        request: _dummy_pb2.ManyRequest17,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse17, _abc.Awaitable[_dummy_pb2.ManyResponse17]]: ...

    def Method18(
        self,
        request: _dummy_pb2.ManyRequest18,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse18, _abc.Awaitable[_dummy_pb2.ManyResponse18]]: ...

    def Method19(
        self,
        request: _dummy_pb2.ManyRequest19,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse19, _abc.Awaitable[_dummy_pb2.ManyResponse19]]: ...

    def Method20(
        self,
        request: _dummy_pb2.ManyRequest20,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse20, _abc.Awaitable[_dummy_pb2.ManyResponse20]]: ...

    def Method21(
        self,
        request: _dummy_pb2.ManyRequest21,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse21, _abc.Awaitable[_dummy_pb2.ManyResponse21]]: ...

    def Method22(
        self,
        request: _dummy_pb2.ManyRequest22,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse22, _abc.Awaitable[_dummy_pb2.ManyResponse22]]: ...

    def Method23(
        self,
        request: _dummy_pb2.ManyRequest23,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse23, _abc.Awaitable[_dummy_pb2.ManyResponse23]]: ...

    def Method24(
        self,
        request: _dummy_pb2.ManyRequest24,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse24, _abc.Awaitable[_dummy_pb2.ManyResponse24]]: ...

    def Method25(
        self,
        request: _dummy_pb2.ManyRequest25,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse25, _abc.Awaitable[_dummy_pb2.ManyResponse25]]: ...

    def Method26(
        self,
        request: _dummy_pb2.ManyRequest26,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse26, _abc.Awaitable[_dummy_pb2.ManyResponse26]]: ...

    def Method27(
        self,
        request: _dummy_pb2.ManyRequest27,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse27, _abc.Awaitable[_dummy_pb2.ManyResponse27]]: ...

    def Method28(
        self,
        request: _dummy_pb2.ManyRequest28,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse28, _abc.Awaitable[_dummy_pb2.ManyResponse28]]: ...

    def Method29(
        self,
        request: _dummy_pb2.ManyRequest29,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse29, _abc.Awaitable[_dummy_pb2.ManyResponse29]]: ...

    def Method30(
        self,
        request: _dummy_pb2.ManyRequest30,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse30, _abc.Awaitable[_dummy_pb2.ManyResponse30]]: ...

    def Method31(
        self,
        request: _dummy_pb2.ManyRequest31,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse31, _abc.Awaitable[_dummy_pb2.ManyResponse31]]: ...

    def Method32(
        self,
        request: _dummy_pb2.ManyRequest32,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse32, _abc.Awaitable[_dummy_pb2.ManyResponse32]]: ...

    def Method33(
        self,
        request: _dummy_pb2.ManyRequest33,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse33, _abc.Awaitable[_dummy_pb2.ManyResponse33]]: ...

    def Method34(
        self,
        request: _dummy_pb2.ManyRequest34,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse34, _abc.Awaitable[_dummy_pb2.ManyResponse34]]: ...

    def Method35(
        self,
        request: _dummy_pb2.ManyRequest35,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse35, _abc.Awaitable[_dummy_pb2.ManyResponse35]]: ...

    def Method36(
        self,
        request: _dummy_pb2.ManyRequest36,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse36, _abc.Awaitable[_dummy_pb2.ManyResponse36]]: ...

    def Method37(
        self,
        request: _dummy_pb2.ManyRequest37,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse37, _abc.Awaitable[_dummy_pb2.ManyResponse37]]: ...

    def Method38(
        self,
        request: _dummy_pb2.ManyRequest38,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse38, _abc.Awaitable[_dummy_pb2.ManyResponse38]]: ...

    def Method39(
        self,
        request: _dummy_pb2.ManyRequest39,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse39, _abc.Awaitable[_dummy_pb2.ManyResponse39]]: ...

    def Method40(
        self,
        request: _dummy_pb2.ManyRequest40,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse40, _abc.Awaitable[_dummy_pb2.ManyResponse40]]: ...

    def Method41(
        self,
        request: _dummy_pb2.ManyRequest41,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse41, _abc.Awaitable[_dummy_pb2.ManyResponse41]]: ...

    def Method42(
        self,
        request: _dummy_pb2.ManyRequest42,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse42, _abc.Awaitable[_dummy_pb2.ManyResponse42]]: ...

    def Method43(
        self,
        request: _dummy_pb2.ManyRequest43,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse43, _abc.Awaitable[_dummy_pb2.ManyResponse43]]: ...

    def Method44(
        self,
        request: _dummy_pb2.ManyRequest44,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse44, _abc.Awaitable[_dummy_pb2.ManyResponse44]]: ...

    def Method45(
        self,
        request: _dummy_pb2.ManyRequest45,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse45, _abc.Awaitable[_dummy_pb2.ManyResponse45]]: ...

    def Method46(
        self,
        request: _dummy_pb2.ManyRequest46,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse46, _abc.Awaitable[_dummy_pb2.ManyResponse46]]: ...

    def Method47(
        self,
        request: _dummy_pb2.ManyRequest47,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse47, _abc.Awaitable[_dummy_pb2.ManyResponse47]]: ...

    def Method48(
        self,
        request: _dummy_pb2.ManyRequest48,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse48, _abc.Awaitable[_dummy_pb2.ManyResponse48]]: ...

    def Method49(
        self,
        request: _dummy_pb2.ManyRequest49,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse49, _abc.Awaitable[_dummy_pb2.ManyResponse49]]: ...

    def Method50(
        self,
        request: _dummy_pb2.ManyRequest50,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse50, _abc.Awaitable[_dummy_pb2.ManyResponse50]]: ...

    def Method51(
        self,
        request: _dummy_pb2.ManyRequest51,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse51, _abc.Awaitable[_dummy_pb2.ManyResponse51]]: ...

    def Method52(
        self,
        request: _dummy_pb2.ManyRequest52,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse52, _abc.Awaitable[_dummy_pb2.ManyResponse52]]: ...

    def Method53(
        self,
        request: _dummy_pb2.ManyRequest53,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse53, _abc.Awaitable[_dummy_pb2.ManyResponse53]]: ...

    def Method54(
        self,
        request: _dummy_pb2.ManyRequest54,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse54, _abc.Awaitable[_dummy_pb2.ManyResponse54]]: ...

    def Method55(
        self,
        request: _dummy_pb2.ManyRequest55,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse55, _abc.Awaitable[_dummy_pb2.ManyResponse55]]: ...

    def Method56(
        self,
        request: _dummy_pb2.ManyRequest56,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse56, _abc.Awaitable[_dummy_pb2.ManyResponse56]]: ...

    def Method57(
        self,
        request: _dummy_pb2.ManyRequest57,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse57, _abc.Awaitable[_dummy_pb2.ManyResponse57]]: ...

    def Method58(
        self,
        request: _dummy_pb2.ManyRequest58,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse58, _abc.Awaitable[_dummy_pb2.ManyResponse58]]: ...

    def Method59(
        self,
        request: _dummy_pb2.ManyRequest59,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse59, _abc.Awaitable[_dummy_pb2.ManyResponse59]]: ...

    def Method60(
        self,
        request: _dummy_pb2.ManyRequest60,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse60, _abc.Awaitable[_dummy_pb2.ManyResponse60]]: ...

    def Method61(
        self,
        request: _dummy_pb2.ManyRequest61,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse61, _abc.Awaitable[_dummy_pb2.ManyResponse61]]: ...

    def Method62(
        self,
        request: _dummy_pb2.ManyRequest62,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse62, _abc.Awaitable[_dummy_pb2.ManyResponse62]]: ...

    def Method63(
        self,
        request: _dummy_pb2.ManyRequest63,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse63, _abc.Awaitable[_dummy_pb2.ManyResponse63]]: ...

    def Method64(
        self,
        request: _dummy_pb2.ManyRequest64,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse64, _abc.Awaitable[_dummy_pb2.ManyResponse64]]: ...

    def Method65(
        self,
        request: _dummy_pb2.ManyRequest65,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse65, _abc.Awaitable[_dummy_pb2.ManyResponse65]]: ...

    def Method66(
        self,
        request: _dummy_pb2.ManyRequest66,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse66, _abc.Awaitable[_dummy_pb2.ManyResponse66]]: ...

    def Method67(
        self,
        request: _dummy_pb2.ManyRequest67,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse67, _abc.Awaitable[_dummy_pb2.ManyResponse67]]: ...

    def Method68(
        self,
        request: _dummy_pb2.ManyRequest68,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse68, _abc.Awaitable[_dummy_pb2.ManyResponse68]]: ...

    def Method69(
        self,
        request: _dummy_pb2.ManyRequest69,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse69, _abc.Awaitable[_dummy_pb2.ManyResponse69]]: ...

    def Method70(
        self,
        request: _dummy_pb2.ManyRequest70,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse70, _abc.Awaitable[_dummy_pb2.ManyResponse70]]: ...

    def Method71(
        self,
        request: _dummy_pb2.ManyRequest71,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse71, _abc.Awaitable[_dummy_pb2.ManyResponse71]]: ...

    def Method72(
        self,
        request: _dummy_pb2.ManyRequest72,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse72, _abc.Awaitable[_dummy_pb2.ManyResponse72]]: ...

    def Method73(
        self,
        request: _dummy_pb2.ManyRequest73,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse73, _abc.Awaitable[_dummy_pb2.ManyResponse73]]: ...

    def Method74(
        self,
        request: _dummy_pb2.ManyRequest74,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse74, _abc.Awaitable[_dummy_pb2.ManyResponse74]]: ...

    def Method75(
        self,
        request: _dummy_pb2.ManyRequest75,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse75, _abc.Awaitable[_dummy_pb2.ManyResponse75]]: ...

    def Method76(
        self,
        request: _dummy_pb2.ManyRequest76,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse76, _abc.Awaitable[_dummy_pb2.ManyResponse76]]: ...

    def Method77(
        self,
        request: _dummy_pb2.ManyRequest77,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse77, _abc.Awaitable[_dummy_pb2.ManyResponse77]]: ...

    def Method78(
        self,
        request: _dummy_pb2.ManyRequest78,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse78, _abc.Awaitable[_dummy_pb2.ManyResponse78]]: ...

    def Method79(
        self,
        request: _dummy_pb2.ManyRequest79,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse79, _abc.Awaitable[_dummy_pb2.ManyResponse79]]: ...

    def Method80(
        self,
        request: _dummy_pb2.ManyRequest80,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse80, _abc.Awaitable[_dummy_pb2.ManyResponse80]]: ...

    def Method81(
        self,
        request: _dummy_pb2.ManyRequest81,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse81, _abc.Awaitable[_dummy_pb2.ManyResponse81]]: ...

    def Method82(
        self,
        request: _dummy_pb2.ManyRequest82,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse82, _abc.Awaitable[_dummy_pb2.ManyResponse82]]: ...

    def Method83(
        self,
        request: _dummy_pb2.ManyRequest83,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse83, _abc.Awaitable[_dummy_pb2.ManyResponse83]]: ...

    def Method84(
        self,
        request: _dummy_pb2.ManyRequest84,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse84, _abc.Awaitable[_dummy_pb2.ManyResponse84]]: ...

    def Method85(
        self,
        request: _dummy_pb2.ManyRequest85,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse85, _abc.Awaitable[_dummy_pb2.ManyResponse85]]: ...

    def Method86(
        self,
        request: _dummy_pb2.ManyRequest86,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse86, _abc.Awaitable[_dummy_pb2.ManyResponse86]]: ...

    def Method87(
        self,
        request: _dummy_pb2.ManyRequest87,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse87, _abc.Awaitable[_dummy_pb2.ManyResponse87]]: ...

    def Method88(
        self,
        request: _dummy_pb2.ManyRequest88,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse88, _abc.Awaitable[_dummy_pb2.ManyResponse88]]: ...

    def Method89(
        self,
        request: _dummy_pb2.ManyRequest89,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse89, _abc.Awaitable[_dummy_pb2.ManyResponse89]]: ...

    def Method90(
        self,
        request: _dummy_pb2.ManyRequest90,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse90, _abc.Awaitable[_dummy_pb2.ManyResponse90]]: ...

    def Method91(
        self,
        request: _dummy_pb2.ManyRequest91,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse91, _abc.Awaitable[_dummy_pb2.ManyResponse91]]: ...

    def Method92(
        self,
        request: _dummy_pb2.ManyRequest92,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse92, _abc.Awaitable[_dummy_pb2.ManyResponse92]]: ...

    def Method93(
        self,
        request: _dummy_pb2.ManyRequest93,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse93, _abc.Awaitable[_dummy_pb2.ManyResponse93]]: ...

    def Method94(
        self,
        request: _dummy_pb2.ManyRequest94,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse94, _abc.Awaitable[_dummy_pb2.ManyResponse94]]: ...

    def Method95(
        self,
        request: _dummy_pb2.ManyRequest95,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse95, _abc.Awaitable[_dummy_pb2.ManyResponse95]]: ...

    def Method96(
        self,
        request: _dummy_pb2.ManyRequest96,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse96, _abc.Awaitable[_dummy_pb2.ManyResponse96]]: ...

    def Method97(
        self,
        request: _dummy_pb2.ManyRequest97,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse97, _abc.Awaitable[_dummy_pb2.ManyResponse97]]: ...

    def Method98(
        self,
        request: _dummy_pb2.ManyRequest98,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse98, _abc.Awaitable[_dummy_pb2.ManyResponse98]]: ...

    def Method99(
        self,
        request: _dummy_pb2.ManyRequest99,
        context: _ServicerContext,
    ) -> _typing.Union[_dummy_pb2.ManyResponse99, _abc.Awaitable[_dummy_pb2.ManyResponse99]]: ...

def add_ManyRPCsServiceServicer_to_server(servicer: ManyRPCsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class EmptyServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EmptyServiceAsyncStub: ...

@_typing.type_check_only
class EmptyServiceAsyncStub(EmptyServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...

class EmptyServiceServicer:
    ...

def add_EmptyServiceServicer_to_server(servicer: EmptyServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
