"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
https://github.com/vmagamedov/grpclib/blob/master/tests/dummy.proto"""

import abc
import collections.abc
import grpc
import grpc.aio
import sys
import testproto.grpc.dummy_pb2
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

if sys.version_info >= (3, 13):
    from warnings import deprecated
else:
    from typing_extensions import deprecated

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DummyServiceStub:
    """DummyService"""

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> _DummyServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> _DummyServiceStubAsync: ...
    UnaryUnary: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]]
    UnaryStream: typing.Union[grpc.UnaryStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply], grpc.aio.UnaryStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]]
    StreamUnary: typing.Union[grpc.StreamUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply], grpc.aio.StreamUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]]
    StreamStream: typing.Union[grpc.StreamStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply], grpc.aio.StreamStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]]

@typing.type_check_only
class _DummyServiceStub(DummyServiceStub):
    def __init__(self, channel: grpc.Channel) -> None: ...
    UnaryUnary: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]
    UnaryStream: grpc.UnaryStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]
    StreamUnary: grpc.StreamUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]
    StreamStream: grpc.StreamStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]

@typing.type_check_only
class _DummyServiceStubAsync(DummyServiceStub):
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    UnaryUnary: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]
    UnaryStream: grpc.aio.UnaryStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]
    StreamUnary: grpc.aio.StreamUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]
    StreamStream: grpc.aio.StreamStreamMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]

DummyServiceAsyncStub: typing_extensions.TypeAlias = _DummyServiceStubAsync

class DummyServiceServicer:
    """DummyService"""

    def UnaryUnary(
        self,
        request: testproto.grpc.dummy_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.DummyReply, collections.abc.Awaitable[testproto.grpc.dummy_pb2.DummyReply]]:
        """UnaryUnary"""

    def UnaryStream(
        self,
        request: testproto.grpc.dummy_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[testproto.grpc.dummy_pb2.DummyReply], collections.abc.AsyncIterator[testproto.grpc.dummy_pb2.DummyReply]]:
        """UnaryStream"""

    def StreamUnary(
        self,
        request_iterator: _MaybeAsyncIterator[testproto.grpc.dummy_pb2.DummyRequest],
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.DummyReply, collections.abc.Awaitable[testproto.grpc.dummy_pb2.DummyReply]]:
        """StreamUnary"""

    def StreamStream(
        self,
        request_iterator: _MaybeAsyncIterator[testproto.grpc.dummy_pb2.DummyRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[testproto.grpc.dummy_pb2.DummyReply], collections.abc.AsyncIterator[testproto.grpc.dummy_pb2.DummyReply]]:
        """StreamStream"""

def add_DummyServiceServicer_to_server(servicer: DummyServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

@deprecated("""This service is deprecated""")
class DeprecatedServiceStub:
    """Marking the service as deprecated"""

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> _DeprecatedServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> _DeprecatedServiceStubAsync: ...
    DeprecatedMethod: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DeprecatedRequest, testproto.grpc.dummy_pb2.DummyReply], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DeprecatedRequest, testproto.grpc.dummy_pb2.DummyReply]]
    DeprecatedMethodNotDeprecatedRequest: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]]

@typing.type_check_only
class _DeprecatedServiceStub(DeprecatedServiceStub):
    def __init__(self, channel: grpc.Channel) -> None: ...
    DeprecatedMethod: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DeprecatedRequest, testproto.grpc.dummy_pb2.DummyReply]
    DeprecatedMethodNotDeprecatedRequest: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]

@typing.type_check_only
class _DeprecatedServiceStubAsync(DeprecatedServiceStub):
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    DeprecatedMethod: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DeprecatedRequest, testproto.grpc.dummy_pb2.DummyReply]
    DeprecatedMethodNotDeprecatedRequest: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.DummyRequest, testproto.grpc.dummy_pb2.DummyReply]

DeprecatedServiceAsyncStub: typing_extensions.TypeAlias = _DeprecatedServiceStubAsync

@deprecated("""This service is deprecated""")
class DeprecatedServiceServicer:
    """Marking the service as deprecated"""

    def DeprecatedMethod(
        self,
        request: testproto.grpc.dummy_pb2.DeprecatedRequest,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.DummyReply, collections.abc.Awaitable[testproto.grpc.dummy_pb2.DummyReply]]:
        """DeprecatedMethod"""

    def DeprecatedMethodNotDeprecatedRequest(
        self,
        request: testproto.grpc.dummy_pb2.DummyRequest,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.DummyReply, collections.abc.Awaitable[testproto.grpc.dummy_pb2.DummyReply]]:
        """DeprecatedMethodNotDeprecatedRequest"""

@deprecated("""This service is deprecated""")
def add_DeprecatedServiceServicer_to_server(servicer: DeprecatedServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

class ManyRPCsServiceStub:
    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> _ManyRPCsServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> _ManyRPCsServiceStubAsync: ...
    Method1: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest1, testproto.grpc.dummy_pb2.ManyResponse1], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest1, testproto.grpc.dummy_pb2.ManyResponse1]]
    Method2: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest2, testproto.grpc.dummy_pb2.ManyResponse2], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest2, testproto.grpc.dummy_pb2.ManyResponse2]]
    Method3: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest3, testproto.grpc.dummy_pb2.ManyResponse3], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest3, testproto.grpc.dummy_pb2.ManyResponse3]]
    Method4: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest4, testproto.grpc.dummy_pb2.ManyResponse4], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest4, testproto.grpc.dummy_pb2.ManyResponse4]]
    Method5: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest5, testproto.grpc.dummy_pb2.ManyResponse5], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest5, testproto.grpc.dummy_pb2.ManyResponse5]]
    Method6: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest6, testproto.grpc.dummy_pb2.ManyResponse6], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest6, testproto.grpc.dummy_pb2.ManyResponse6]]
    Method7: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest7, testproto.grpc.dummy_pb2.ManyResponse7], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest7, testproto.grpc.dummy_pb2.ManyResponse7]]
    Method8: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest8, testproto.grpc.dummy_pb2.ManyResponse8], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest8, testproto.grpc.dummy_pb2.ManyResponse8]]
    Method9: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest9, testproto.grpc.dummy_pb2.ManyResponse9], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest9, testproto.grpc.dummy_pb2.ManyResponse9]]
    Method10: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest10, testproto.grpc.dummy_pb2.ManyResponse10], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest10, testproto.grpc.dummy_pb2.ManyResponse10]]
    Method11: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest11, testproto.grpc.dummy_pb2.ManyResponse11], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest11, testproto.grpc.dummy_pb2.ManyResponse11]]
    Method12: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest12, testproto.grpc.dummy_pb2.ManyResponse12], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest12, testproto.grpc.dummy_pb2.ManyResponse12]]
    Method13: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest13, testproto.grpc.dummy_pb2.ManyResponse13], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest13, testproto.grpc.dummy_pb2.ManyResponse13]]
    Method14: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest14, testproto.grpc.dummy_pb2.ManyResponse14], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest14, testproto.grpc.dummy_pb2.ManyResponse14]]
    Method15: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest15, testproto.grpc.dummy_pb2.ManyResponse15], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest15, testproto.grpc.dummy_pb2.ManyResponse15]]
    Method16: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest16, testproto.grpc.dummy_pb2.ManyResponse16], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest16, testproto.grpc.dummy_pb2.ManyResponse16]]
    Method17: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest17, testproto.grpc.dummy_pb2.ManyResponse17], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest17, testproto.grpc.dummy_pb2.ManyResponse17]]
    Method18: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest18, testproto.grpc.dummy_pb2.ManyResponse18], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest18, testproto.grpc.dummy_pb2.ManyResponse18]]
    Method19: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest19, testproto.grpc.dummy_pb2.ManyResponse19], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest19, testproto.grpc.dummy_pb2.ManyResponse19]]
    Method20: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest20, testproto.grpc.dummy_pb2.ManyResponse20], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest20, testproto.grpc.dummy_pb2.ManyResponse20]]
    Method21: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest21, testproto.grpc.dummy_pb2.ManyResponse21], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest21, testproto.grpc.dummy_pb2.ManyResponse21]]
    Method22: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest22, testproto.grpc.dummy_pb2.ManyResponse22], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest22, testproto.grpc.dummy_pb2.ManyResponse22]]
    Method23: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest23, testproto.grpc.dummy_pb2.ManyResponse23], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest23, testproto.grpc.dummy_pb2.ManyResponse23]]
    Method24: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest24, testproto.grpc.dummy_pb2.ManyResponse24], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest24, testproto.grpc.dummy_pb2.ManyResponse24]]
    Method25: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest25, testproto.grpc.dummy_pb2.ManyResponse25], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest25, testproto.grpc.dummy_pb2.ManyResponse25]]
    Method26: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest26, testproto.grpc.dummy_pb2.ManyResponse26], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest26, testproto.grpc.dummy_pb2.ManyResponse26]]
    Method27: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest27, testproto.grpc.dummy_pb2.ManyResponse27], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest27, testproto.grpc.dummy_pb2.ManyResponse27]]
    Method28: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest28, testproto.grpc.dummy_pb2.ManyResponse28], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest28, testproto.grpc.dummy_pb2.ManyResponse28]]
    Method29: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest29, testproto.grpc.dummy_pb2.ManyResponse29], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest29, testproto.grpc.dummy_pb2.ManyResponse29]]
    Method30: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest30, testproto.grpc.dummy_pb2.ManyResponse30], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest30, testproto.grpc.dummy_pb2.ManyResponse30]]
    Method31: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest31, testproto.grpc.dummy_pb2.ManyResponse31], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest31, testproto.grpc.dummy_pb2.ManyResponse31]]
    Method32: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest32, testproto.grpc.dummy_pb2.ManyResponse32], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest32, testproto.grpc.dummy_pb2.ManyResponse32]]
    Method33: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest33, testproto.grpc.dummy_pb2.ManyResponse33], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest33, testproto.grpc.dummy_pb2.ManyResponse33]]
    Method34: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest34, testproto.grpc.dummy_pb2.ManyResponse34], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest34, testproto.grpc.dummy_pb2.ManyResponse34]]
    Method35: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest35, testproto.grpc.dummy_pb2.ManyResponse35], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest35, testproto.grpc.dummy_pb2.ManyResponse35]]
    Method36: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest36, testproto.grpc.dummy_pb2.ManyResponse36], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest36, testproto.grpc.dummy_pb2.ManyResponse36]]
    Method37: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest37, testproto.grpc.dummy_pb2.ManyResponse37], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest37, testproto.grpc.dummy_pb2.ManyResponse37]]
    Method38: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest38, testproto.grpc.dummy_pb2.ManyResponse38], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest38, testproto.grpc.dummy_pb2.ManyResponse38]]
    Method39: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest39, testproto.grpc.dummy_pb2.ManyResponse39], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest39, testproto.grpc.dummy_pb2.ManyResponse39]]
    Method40: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest40, testproto.grpc.dummy_pb2.ManyResponse40], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest40, testproto.grpc.dummy_pb2.ManyResponse40]]
    Method41: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest41, testproto.grpc.dummy_pb2.ManyResponse41], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest41, testproto.grpc.dummy_pb2.ManyResponse41]]
    Method42: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest42, testproto.grpc.dummy_pb2.ManyResponse42], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest42, testproto.grpc.dummy_pb2.ManyResponse42]]
    Method43: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest43, testproto.grpc.dummy_pb2.ManyResponse43], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest43, testproto.grpc.dummy_pb2.ManyResponse43]]
    Method44: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest44, testproto.grpc.dummy_pb2.ManyResponse44], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest44, testproto.grpc.dummy_pb2.ManyResponse44]]
    Method45: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest45, testproto.grpc.dummy_pb2.ManyResponse45], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest45, testproto.grpc.dummy_pb2.ManyResponse45]]
    Method46: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest46, testproto.grpc.dummy_pb2.ManyResponse46], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest46, testproto.grpc.dummy_pb2.ManyResponse46]]
    Method47: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest47, testproto.grpc.dummy_pb2.ManyResponse47], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest47, testproto.grpc.dummy_pb2.ManyResponse47]]
    Method48: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest48, testproto.grpc.dummy_pb2.ManyResponse48], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest48, testproto.grpc.dummy_pb2.ManyResponse48]]
    Method49: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest49, testproto.grpc.dummy_pb2.ManyResponse49], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest49, testproto.grpc.dummy_pb2.ManyResponse49]]
    Method50: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest50, testproto.grpc.dummy_pb2.ManyResponse50], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest50, testproto.grpc.dummy_pb2.ManyResponse50]]
    Method51: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest51, testproto.grpc.dummy_pb2.ManyResponse51], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest51, testproto.grpc.dummy_pb2.ManyResponse51]]
    Method52: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest52, testproto.grpc.dummy_pb2.ManyResponse52], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest52, testproto.grpc.dummy_pb2.ManyResponse52]]
    Method53: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest53, testproto.grpc.dummy_pb2.ManyResponse53], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest53, testproto.grpc.dummy_pb2.ManyResponse53]]
    Method54: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest54, testproto.grpc.dummy_pb2.ManyResponse54], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest54, testproto.grpc.dummy_pb2.ManyResponse54]]
    Method55: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest55, testproto.grpc.dummy_pb2.ManyResponse55], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest55, testproto.grpc.dummy_pb2.ManyResponse55]]
    Method56: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest56, testproto.grpc.dummy_pb2.ManyResponse56], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest56, testproto.grpc.dummy_pb2.ManyResponse56]]
    Method57: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest57, testproto.grpc.dummy_pb2.ManyResponse57], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest57, testproto.grpc.dummy_pb2.ManyResponse57]]
    Method58: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest58, testproto.grpc.dummy_pb2.ManyResponse58], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest58, testproto.grpc.dummy_pb2.ManyResponse58]]
    Method59: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest59, testproto.grpc.dummy_pb2.ManyResponse59], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest59, testproto.grpc.dummy_pb2.ManyResponse59]]
    Method60: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest60, testproto.grpc.dummy_pb2.ManyResponse60], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest60, testproto.grpc.dummy_pb2.ManyResponse60]]
    Method61: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest61, testproto.grpc.dummy_pb2.ManyResponse61], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest61, testproto.grpc.dummy_pb2.ManyResponse61]]
    Method62: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest62, testproto.grpc.dummy_pb2.ManyResponse62], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest62, testproto.grpc.dummy_pb2.ManyResponse62]]
    Method63: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest63, testproto.grpc.dummy_pb2.ManyResponse63], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest63, testproto.grpc.dummy_pb2.ManyResponse63]]
    Method64: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest64, testproto.grpc.dummy_pb2.ManyResponse64], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest64, testproto.grpc.dummy_pb2.ManyResponse64]]
    Method65: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest65, testproto.grpc.dummy_pb2.ManyResponse65], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest65, testproto.grpc.dummy_pb2.ManyResponse65]]
    Method66: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest66, testproto.grpc.dummy_pb2.ManyResponse66], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest66, testproto.grpc.dummy_pb2.ManyResponse66]]
    Method67: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest67, testproto.grpc.dummy_pb2.ManyResponse67], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest67, testproto.grpc.dummy_pb2.ManyResponse67]]
    Method68: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest68, testproto.grpc.dummy_pb2.ManyResponse68], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest68, testproto.grpc.dummy_pb2.ManyResponse68]]
    Method69: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest69, testproto.grpc.dummy_pb2.ManyResponse69], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest69, testproto.grpc.dummy_pb2.ManyResponse69]]
    Method70: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest70, testproto.grpc.dummy_pb2.ManyResponse70], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest70, testproto.grpc.dummy_pb2.ManyResponse70]]
    Method71: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest71, testproto.grpc.dummy_pb2.ManyResponse71], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest71, testproto.grpc.dummy_pb2.ManyResponse71]]
    Method72: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest72, testproto.grpc.dummy_pb2.ManyResponse72], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest72, testproto.grpc.dummy_pb2.ManyResponse72]]
    Method73: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest73, testproto.grpc.dummy_pb2.ManyResponse73], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest73, testproto.grpc.dummy_pb2.ManyResponse73]]
    Method74: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest74, testproto.grpc.dummy_pb2.ManyResponse74], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest74, testproto.grpc.dummy_pb2.ManyResponse74]]
    Method75: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest75, testproto.grpc.dummy_pb2.ManyResponse75], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest75, testproto.grpc.dummy_pb2.ManyResponse75]]
    Method76: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest76, testproto.grpc.dummy_pb2.ManyResponse76], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest76, testproto.grpc.dummy_pb2.ManyResponse76]]
    Method77: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest77, testproto.grpc.dummy_pb2.ManyResponse77], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest77, testproto.grpc.dummy_pb2.ManyResponse77]]
    Method78: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest78, testproto.grpc.dummy_pb2.ManyResponse78], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest78, testproto.grpc.dummy_pb2.ManyResponse78]]
    Method79: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest79, testproto.grpc.dummy_pb2.ManyResponse79], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest79, testproto.grpc.dummy_pb2.ManyResponse79]]
    Method80: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest80, testproto.grpc.dummy_pb2.ManyResponse80], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest80, testproto.grpc.dummy_pb2.ManyResponse80]]
    Method81: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest81, testproto.grpc.dummy_pb2.ManyResponse81], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest81, testproto.grpc.dummy_pb2.ManyResponse81]]
    Method82: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest82, testproto.grpc.dummy_pb2.ManyResponse82], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest82, testproto.grpc.dummy_pb2.ManyResponse82]]
    Method83: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest83, testproto.grpc.dummy_pb2.ManyResponse83], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest83, testproto.grpc.dummy_pb2.ManyResponse83]]
    Method84: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest84, testproto.grpc.dummy_pb2.ManyResponse84], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest84, testproto.grpc.dummy_pb2.ManyResponse84]]
    Method85: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest85, testproto.grpc.dummy_pb2.ManyResponse85], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest85, testproto.grpc.dummy_pb2.ManyResponse85]]
    Method86: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest86, testproto.grpc.dummy_pb2.ManyResponse86], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest86, testproto.grpc.dummy_pb2.ManyResponse86]]
    Method87: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest87, testproto.grpc.dummy_pb2.ManyResponse87], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest87, testproto.grpc.dummy_pb2.ManyResponse87]]
    Method88: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest88, testproto.grpc.dummy_pb2.ManyResponse88], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest88, testproto.grpc.dummy_pb2.ManyResponse88]]
    Method89: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest89, testproto.grpc.dummy_pb2.ManyResponse89], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest89, testproto.grpc.dummy_pb2.ManyResponse89]]
    Method90: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest90, testproto.grpc.dummy_pb2.ManyResponse90], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest90, testproto.grpc.dummy_pb2.ManyResponse90]]
    Method91: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest91, testproto.grpc.dummy_pb2.ManyResponse91], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest91, testproto.grpc.dummy_pb2.ManyResponse91]]
    Method92: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest92, testproto.grpc.dummy_pb2.ManyResponse92], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest92, testproto.grpc.dummy_pb2.ManyResponse92]]
    Method93: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest93, testproto.grpc.dummy_pb2.ManyResponse93], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest93, testproto.grpc.dummy_pb2.ManyResponse93]]
    Method94: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest94, testproto.grpc.dummy_pb2.ManyResponse94], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest94, testproto.grpc.dummy_pb2.ManyResponse94]]
    Method95: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest95, testproto.grpc.dummy_pb2.ManyResponse95], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest95, testproto.grpc.dummy_pb2.ManyResponse95]]
    Method96: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest96, testproto.grpc.dummy_pb2.ManyResponse96], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest96, testproto.grpc.dummy_pb2.ManyResponse96]]
    Method97: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest97, testproto.grpc.dummy_pb2.ManyResponse97], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest97, testproto.grpc.dummy_pb2.ManyResponse97]]
    Method98: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest98, testproto.grpc.dummy_pb2.ManyResponse98], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest98, testproto.grpc.dummy_pb2.ManyResponse98]]
    Method99: typing.Union[grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest99, testproto.grpc.dummy_pb2.ManyResponse99], grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest99, testproto.grpc.dummy_pb2.ManyResponse99]]

@typing.type_check_only
class _ManyRPCsServiceStub(ManyRPCsServiceStub):
    def __init__(self, channel: grpc.Channel) -> None: ...
    Method1: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest1, testproto.grpc.dummy_pb2.ManyResponse1]
    Method2: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest2, testproto.grpc.dummy_pb2.ManyResponse2]
    Method3: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest3, testproto.grpc.dummy_pb2.ManyResponse3]
    Method4: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest4, testproto.grpc.dummy_pb2.ManyResponse4]
    Method5: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest5, testproto.grpc.dummy_pb2.ManyResponse5]
    Method6: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest6, testproto.grpc.dummy_pb2.ManyResponse6]
    Method7: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest7, testproto.grpc.dummy_pb2.ManyResponse7]
    Method8: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest8, testproto.grpc.dummy_pb2.ManyResponse8]
    Method9: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest9, testproto.grpc.dummy_pb2.ManyResponse9]
    Method10: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest10, testproto.grpc.dummy_pb2.ManyResponse10]
    Method11: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest11, testproto.grpc.dummy_pb2.ManyResponse11]
    Method12: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest12, testproto.grpc.dummy_pb2.ManyResponse12]
    Method13: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest13, testproto.grpc.dummy_pb2.ManyResponse13]
    Method14: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest14, testproto.grpc.dummy_pb2.ManyResponse14]
    Method15: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest15, testproto.grpc.dummy_pb2.ManyResponse15]
    Method16: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest16, testproto.grpc.dummy_pb2.ManyResponse16]
    Method17: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest17, testproto.grpc.dummy_pb2.ManyResponse17]
    Method18: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest18, testproto.grpc.dummy_pb2.ManyResponse18]
    Method19: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest19, testproto.grpc.dummy_pb2.ManyResponse19]
    Method20: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest20, testproto.grpc.dummy_pb2.ManyResponse20]
    Method21: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest21, testproto.grpc.dummy_pb2.ManyResponse21]
    Method22: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest22, testproto.grpc.dummy_pb2.ManyResponse22]
    Method23: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest23, testproto.grpc.dummy_pb2.ManyResponse23]
    Method24: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest24, testproto.grpc.dummy_pb2.ManyResponse24]
    Method25: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest25, testproto.grpc.dummy_pb2.ManyResponse25]
    Method26: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest26, testproto.grpc.dummy_pb2.ManyResponse26]
    Method27: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest27, testproto.grpc.dummy_pb2.ManyResponse27]
    Method28: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest28, testproto.grpc.dummy_pb2.ManyResponse28]
    Method29: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest29, testproto.grpc.dummy_pb2.ManyResponse29]
    Method30: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest30, testproto.grpc.dummy_pb2.ManyResponse30]
    Method31: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest31, testproto.grpc.dummy_pb2.ManyResponse31]
    Method32: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest32, testproto.grpc.dummy_pb2.ManyResponse32]
    Method33: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest33, testproto.grpc.dummy_pb2.ManyResponse33]
    Method34: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest34, testproto.grpc.dummy_pb2.ManyResponse34]
    Method35: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest35, testproto.grpc.dummy_pb2.ManyResponse35]
    Method36: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest36, testproto.grpc.dummy_pb2.ManyResponse36]
    Method37: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest37, testproto.grpc.dummy_pb2.ManyResponse37]
    Method38: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest38, testproto.grpc.dummy_pb2.ManyResponse38]
    Method39: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest39, testproto.grpc.dummy_pb2.ManyResponse39]
    Method40: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest40, testproto.grpc.dummy_pb2.ManyResponse40]
    Method41: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest41, testproto.grpc.dummy_pb2.ManyResponse41]
    Method42: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest42, testproto.grpc.dummy_pb2.ManyResponse42]
    Method43: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest43, testproto.grpc.dummy_pb2.ManyResponse43]
    Method44: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest44, testproto.grpc.dummy_pb2.ManyResponse44]
    Method45: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest45, testproto.grpc.dummy_pb2.ManyResponse45]
    Method46: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest46, testproto.grpc.dummy_pb2.ManyResponse46]
    Method47: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest47, testproto.grpc.dummy_pb2.ManyResponse47]
    Method48: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest48, testproto.grpc.dummy_pb2.ManyResponse48]
    Method49: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest49, testproto.grpc.dummy_pb2.ManyResponse49]
    Method50: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest50, testproto.grpc.dummy_pb2.ManyResponse50]
    Method51: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest51, testproto.grpc.dummy_pb2.ManyResponse51]
    Method52: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest52, testproto.grpc.dummy_pb2.ManyResponse52]
    Method53: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest53, testproto.grpc.dummy_pb2.ManyResponse53]
    Method54: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest54, testproto.grpc.dummy_pb2.ManyResponse54]
    Method55: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest55, testproto.grpc.dummy_pb2.ManyResponse55]
    Method56: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest56, testproto.grpc.dummy_pb2.ManyResponse56]
    Method57: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest57, testproto.grpc.dummy_pb2.ManyResponse57]
    Method58: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest58, testproto.grpc.dummy_pb2.ManyResponse58]
    Method59: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest59, testproto.grpc.dummy_pb2.ManyResponse59]
    Method60: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest60, testproto.grpc.dummy_pb2.ManyResponse60]
    Method61: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest61, testproto.grpc.dummy_pb2.ManyResponse61]
    Method62: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest62, testproto.grpc.dummy_pb2.ManyResponse62]
    Method63: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest63, testproto.grpc.dummy_pb2.ManyResponse63]
    Method64: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest64, testproto.grpc.dummy_pb2.ManyResponse64]
    Method65: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest65, testproto.grpc.dummy_pb2.ManyResponse65]
    Method66: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest66, testproto.grpc.dummy_pb2.ManyResponse66]
    Method67: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest67, testproto.grpc.dummy_pb2.ManyResponse67]
    Method68: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest68, testproto.grpc.dummy_pb2.ManyResponse68]
    Method69: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest69, testproto.grpc.dummy_pb2.ManyResponse69]
    Method70: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest70, testproto.grpc.dummy_pb2.ManyResponse70]
    Method71: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest71, testproto.grpc.dummy_pb2.ManyResponse71]
    Method72: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest72, testproto.grpc.dummy_pb2.ManyResponse72]
    Method73: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest73, testproto.grpc.dummy_pb2.ManyResponse73]
    Method74: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest74, testproto.grpc.dummy_pb2.ManyResponse74]
    Method75: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest75, testproto.grpc.dummy_pb2.ManyResponse75]
    Method76: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest76, testproto.grpc.dummy_pb2.ManyResponse76]
    Method77: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest77, testproto.grpc.dummy_pb2.ManyResponse77]
    Method78: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest78, testproto.grpc.dummy_pb2.ManyResponse78]
    Method79: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest79, testproto.grpc.dummy_pb2.ManyResponse79]
    Method80: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest80, testproto.grpc.dummy_pb2.ManyResponse80]
    Method81: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest81, testproto.grpc.dummy_pb2.ManyResponse81]
    Method82: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest82, testproto.grpc.dummy_pb2.ManyResponse82]
    Method83: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest83, testproto.grpc.dummy_pb2.ManyResponse83]
    Method84: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest84, testproto.grpc.dummy_pb2.ManyResponse84]
    Method85: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest85, testproto.grpc.dummy_pb2.ManyResponse85]
    Method86: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest86, testproto.grpc.dummy_pb2.ManyResponse86]
    Method87: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest87, testproto.grpc.dummy_pb2.ManyResponse87]
    Method88: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest88, testproto.grpc.dummy_pb2.ManyResponse88]
    Method89: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest89, testproto.grpc.dummy_pb2.ManyResponse89]
    Method90: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest90, testproto.grpc.dummy_pb2.ManyResponse90]
    Method91: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest91, testproto.grpc.dummy_pb2.ManyResponse91]
    Method92: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest92, testproto.grpc.dummy_pb2.ManyResponse92]
    Method93: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest93, testproto.grpc.dummy_pb2.ManyResponse93]
    Method94: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest94, testproto.grpc.dummy_pb2.ManyResponse94]
    Method95: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest95, testproto.grpc.dummy_pb2.ManyResponse95]
    Method96: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest96, testproto.grpc.dummy_pb2.ManyResponse96]
    Method97: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest97, testproto.grpc.dummy_pb2.ManyResponse97]
    Method98: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest98, testproto.grpc.dummy_pb2.ManyResponse98]
    Method99: grpc.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest99, testproto.grpc.dummy_pb2.ManyResponse99]

@typing.type_check_only
class _ManyRPCsServiceStubAsync(ManyRPCsServiceStub):
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    Method1: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest1, testproto.grpc.dummy_pb2.ManyResponse1]
    Method2: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest2, testproto.grpc.dummy_pb2.ManyResponse2]
    Method3: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest3, testproto.grpc.dummy_pb2.ManyResponse3]
    Method4: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest4, testproto.grpc.dummy_pb2.ManyResponse4]
    Method5: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest5, testproto.grpc.dummy_pb2.ManyResponse5]
    Method6: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest6, testproto.grpc.dummy_pb2.ManyResponse6]
    Method7: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest7, testproto.grpc.dummy_pb2.ManyResponse7]
    Method8: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest8, testproto.grpc.dummy_pb2.ManyResponse8]
    Method9: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest9, testproto.grpc.dummy_pb2.ManyResponse9]
    Method10: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest10, testproto.grpc.dummy_pb2.ManyResponse10]
    Method11: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest11, testproto.grpc.dummy_pb2.ManyResponse11]
    Method12: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest12, testproto.grpc.dummy_pb2.ManyResponse12]
    Method13: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest13, testproto.grpc.dummy_pb2.ManyResponse13]
    Method14: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest14, testproto.grpc.dummy_pb2.ManyResponse14]
    Method15: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest15, testproto.grpc.dummy_pb2.ManyResponse15]
    Method16: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest16, testproto.grpc.dummy_pb2.ManyResponse16]
    Method17: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest17, testproto.grpc.dummy_pb2.ManyResponse17]
    Method18: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest18, testproto.grpc.dummy_pb2.ManyResponse18]
    Method19: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest19, testproto.grpc.dummy_pb2.ManyResponse19]
    Method20: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest20, testproto.grpc.dummy_pb2.ManyResponse20]
    Method21: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest21, testproto.grpc.dummy_pb2.ManyResponse21]
    Method22: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest22, testproto.grpc.dummy_pb2.ManyResponse22]
    Method23: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest23, testproto.grpc.dummy_pb2.ManyResponse23]
    Method24: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest24, testproto.grpc.dummy_pb2.ManyResponse24]
    Method25: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest25, testproto.grpc.dummy_pb2.ManyResponse25]
    Method26: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest26, testproto.grpc.dummy_pb2.ManyResponse26]
    Method27: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest27, testproto.grpc.dummy_pb2.ManyResponse27]
    Method28: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest28, testproto.grpc.dummy_pb2.ManyResponse28]
    Method29: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest29, testproto.grpc.dummy_pb2.ManyResponse29]
    Method30: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest30, testproto.grpc.dummy_pb2.ManyResponse30]
    Method31: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest31, testproto.grpc.dummy_pb2.ManyResponse31]
    Method32: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest32, testproto.grpc.dummy_pb2.ManyResponse32]
    Method33: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest33, testproto.grpc.dummy_pb2.ManyResponse33]
    Method34: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest34, testproto.grpc.dummy_pb2.ManyResponse34]
    Method35: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest35, testproto.grpc.dummy_pb2.ManyResponse35]
    Method36: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest36, testproto.grpc.dummy_pb2.ManyResponse36]
    Method37: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest37, testproto.grpc.dummy_pb2.ManyResponse37]
    Method38: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest38, testproto.grpc.dummy_pb2.ManyResponse38]
    Method39: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest39, testproto.grpc.dummy_pb2.ManyResponse39]
    Method40: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest40, testproto.grpc.dummy_pb2.ManyResponse40]
    Method41: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest41, testproto.grpc.dummy_pb2.ManyResponse41]
    Method42: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest42, testproto.grpc.dummy_pb2.ManyResponse42]
    Method43: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest43, testproto.grpc.dummy_pb2.ManyResponse43]
    Method44: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest44, testproto.grpc.dummy_pb2.ManyResponse44]
    Method45: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest45, testproto.grpc.dummy_pb2.ManyResponse45]
    Method46: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest46, testproto.grpc.dummy_pb2.ManyResponse46]
    Method47: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest47, testproto.grpc.dummy_pb2.ManyResponse47]
    Method48: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest48, testproto.grpc.dummy_pb2.ManyResponse48]
    Method49: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest49, testproto.grpc.dummy_pb2.ManyResponse49]
    Method50: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest50, testproto.grpc.dummy_pb2.ManyResponse50]
    Method51: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest51, testproto.grpc.dummy_pb2.ManyResponse51]
    Method52: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest52, testproto.grpc.dummy_pb2.ManyResponse52]
    Method53: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest53, testproto.grpc.dummy_pb2.ManyResponse53]
    Method54: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest54, testproto.grpc.dummy_pb2.ManyResponse54]
    Method55: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest55, testproto.grpc.dummy_pb2.ManyResponse55]
    Method56: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest56, testproto.grpc.dummy_pb2.ManyResponse56]
    Method57: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest57, testproto.grpc.dummy_pb2.ManyResponse57]
    Method58: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest58, testproto.grpc.dummy_pb2.ManyResponse58]
    Method59: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest59, testproto.grpc.dummy_pb2.ManyResponse59]
    Method60: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest60, testproto.grpc.dummy_pb2.ManyResponse60]
    Method61: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest61, testproto.grpc.dummy_pb2.ManyResponse61]
    Method62: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest62, testproto.grpc.dummy_pb2.ManyResponse62]
    Method63: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest63, testproto.grpc.dummy_pb2.ManyResponse63]
    Method64: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest64, testproto.grpc.dummy_pb2.ManyResponse64]
    Method65: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest65, testproto.grpc.dummy_pb2.ManyResponse65]
    Method66: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest66, testproto.grpc.dummy_pb2.ManyResponse66]
    Method67: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest67, testproto.grpc.dummy_pb2.ManyResponse67]
    Method68: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest68, testproto.grpc.dummy_pb2.ManyResponse68]
    Method69: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest69, testproto.grpc.dummy_pb2.ManyResponse69]
    Method70: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest70, testproto.grpc.dummy_pb2.ManyResponse70]
    Method71: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest71, testproto.grpc.dummy_pb2.ManyResponse71]
    Method72: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest72, testproto.grpc.dummy_pb2.ManyResponse72]
    Method73: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest73, testproto.grpc.dummy_pb2.ManyResponse73]
    Method74: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest74, testproto.grpc.dummy_pb2.ManyResponse74]
    Method75: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest75, testproto.grpc.dummy_pb2.ManyResponse75]
    Method76: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest76, testproto.grpc.dummy_pb2.ManyResponse76]
    Method77: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest77, testproto.grpc.dummy_pb2.ManyResponse77]
    Method78: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest78, testproto.grpc.dummy_pb2.ManyResponse78]
    Method79: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest79, testproto.grpc.dummy_pb2.ManyResponse79]
    Method80: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest80, testproto.grpc.dummy_pb2.ManyResponse80]
    Method81: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest81, testproto.grpc.dummy_pb2.ManyResponse81]
    Method82: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest82, testproto.grpc.dummy_pb2.ManyResponse82]
    Method83: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest83, testproto.grpc.dummy_pb2.ManyResponse83]
    Method84: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest84, testproto.grpc.dummy_pb2.ManyResponse84]
    Method85: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest85, testproto.grpc.dummy_pb2.ManyResponse85]
    Method86: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest86, testproto.grpc.dummy_pb2.ManyResponse86]
    Method87: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest87, testproto.grpc.dummy_pb2.ManyResponse87]
    Method88: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest88, testproto.grpc.dummy_pb2.ManyResponse88]
    Method89: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest89, testproto.grpc.dummy_pb2.ManyResponse89]
    Method90: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest90, testproto.grpc.dummy_pb2.ManyResponse90]
    Method91: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest91, testproto.grpc.dummy_pb2.ManyResponse91]
    Method92: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest92, testproto.grpc.dummy_pb2.ManyResponse92]
    Method93: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest93, testproto.grpc.dummy_pb2.ManyResponse93]
    Method94: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest94, testproto.grpc.dummy_pb2.ManyResponse94]
    Method95: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest95, testproto.grpc.dummy_pb2.ManyResponse95]
    Method96: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest96, testproto.grpc.dummy_pb2.ManyResponse96]
    Method97: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest97, testproto.grpc.dummy_pb2.ManyResponse97]
    Method98: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest98, testproto.grpc.dummy_pb2.ManyResponse98]
    Method99: grpc.aio.UnaryUnaryMultiCallable[testproto.grpc.dummy_pb2.ManyRequest99, testproto.grpc.dummy_pb2.ManyResponse99]

ManyRPCsServiceAsyncStub: typing_extensions.TypeAlias = _ManyRPCsServiceStubAsync

class ManyRPCsServiceServicer:
    def Method1(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest1,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse1, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse1]]: ...

    def Method2(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest2,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse2, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse2]]: ...

    def Method3(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest3,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse3, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse3]]: ...

    def Method4(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest4,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse4, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse4]]: ...

    def Method5(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest5,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse5, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse5]]: ...

    def Method6(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest6,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse6, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse6]]: ...

    def Method7(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest7,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse7, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse7]]: ...

    def Method8(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest8,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse8, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse8]]: ...

    def Method9(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest9,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse9, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse9]]: ...

    def Method10(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest10,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse10, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse10]]: ...

    def Method11(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest11,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse11, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse11]]: ...

    def Method12(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest12,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse12, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse12]]: ...

    def Method13(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest13,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse13, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse13]]: ...

    def Method14(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest14,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse14, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse14]]: ...

    def Method15(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest15,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse15, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse15]]: ...

    def Method16(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest16,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse16, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse16]]: ...

    def Method17(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest17,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse17, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse17]]: ...

    def Method18(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest18,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse18, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse18]]: ...

    def Method19(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest19,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse19, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse19]]: ...

    def Method20(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest20,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse20, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse20]]: ...

    def Method21(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest21,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse21, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse21]]: ...

    def Method22(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest22,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse22, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse22]]: ...

    def Method23(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest23,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse23, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse23]]: ...

    def Method24(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest24,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse24, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse24]]: ...

    def Method25(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest25,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse25, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse25]]: ...

    def Method26(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest26,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse26, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse26]]: ...

    def Method27(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest27,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse27, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse27]]: ...

    def Method28(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest28,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse28, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse28]]: ...

    def Method29(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest29,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse29, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse29]]: ...

    def Method30(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest30,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse30, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse30]]: ...

    def Method31(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest31,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse31, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse31]]: ...

    def Method32(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest32,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse32, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse32]]: ...

    def Method33(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest33,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse33, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse33]]: ...

    def Method34(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest34,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse34, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse34]]: ...

    def Method35(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest35,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse35, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse35]]: ...

    def Method36(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest36,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse36, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse36]]: ...

    def Method37(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest37,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse37, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse37]]: ...

    def Method38(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest38,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse38, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse38]]: ...

    def Method39(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest39,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse39, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse39]]: ...

    def Method40(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest40,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse40, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse40]]: ...

    def Method41(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest41,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse41, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse41]]: ...

    def Method42(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest42,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse42, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse42]]: ...

    def Method43(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest43,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse43, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse43]]: ...

    def Method44(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest44,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse44, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse44]]: ...

    def Method45(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest45,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse45, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse45]]: ...

    def Method46(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest46,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse46, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse46]]: ...

    def Method47(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest47,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse47, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse47]]: ...

    def Method48(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest48,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse48, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse48]]: ...

    def Method49(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest49,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse49, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse49]]: ...

    def Method50(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest50,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse50, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse50]]: ...

    def Method51(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest51,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse51, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse51]]: ...

    def Method52(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest52,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse52, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse52]]: ...

    def Method53(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest53,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse53, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse53]]: ...

    def Method54(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest54,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse54, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse54]]: ...

    def Method55(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest55,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse55, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse55]]: ...

    def Method56(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest56,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse56, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse56]]: ...

    def Method57(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest57,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse57, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse57]]: ...

    def Method58(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest58,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse58, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse58]]: ...

    def Method59(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest59,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse59, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse59]]: ...

    def Method60(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest60,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse60, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse60]]: ...

    def Method61(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest61,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse61, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse61]]: ...

    def Method62(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest62,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse62, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse62]]: ...

    def Method63(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest63,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse63, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse63]]: ...

    def Method64(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest64,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse64, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse64]]: ...

    def Method65(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest65,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse65, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse65]]: ...

    def Method66(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest66,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse66, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse66]]: ...

    def Method67(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest67,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse67, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse67]]: ...

    def Method68(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest68,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse68, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse68]]: ...

    def Method69(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest69,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse69, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse69]]: ...

    def Method70(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest70,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse70, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse70]]: ...

    def Method71(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest71,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse71, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse71]]: ...

    def Method72(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest72,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse72, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse72]]: ...

    def Method73(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest73,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse73, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse73]]: ...

    def Method74(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest74,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse74, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse74]]: ...

    def Method75(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest75,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse75, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse75]]: ...

    def Method76(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest76,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse76, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse76]]: ...

    def Method77(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest77,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse77, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse77]]: ...

    def Method78(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest78,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse78, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse78]]: ...

    def Method79(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest79,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse79, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse79]]: ...

    def Method80(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest80,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse80, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse80]]: ...

    def Method81(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest81,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse81, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse81]]: ...

    def Method82(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest82,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse82, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse82]]: ...

    def Method83(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest83,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse83, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse83]]: ...

    def Method84(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest84,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse84, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse84]]: ...

    def Method85(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest85,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse85, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse85]]: ...

    def Method86(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest86,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse86, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse86]]: ...

    def Method87(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest87,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse87, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse87]]: ...

    def Method88(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest88,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse88, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse88]]: ...

    def Method89(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest89,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse89, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse89]]: ...

    def Method90(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest90,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse90, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse90]]: ...

    def Method91(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest91,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse91, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse91]]: ...

    def Method92(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest92,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse92, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse92]]: ...

    def Method93(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest93,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse93, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse93]]: ...

    def Method94(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest94,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse94, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse94]]: ...

    def Method95(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest95,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse95, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse95]]: ...

    def Method96(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest96,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse96, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse96]]: ...

    def Method97(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest97,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse97, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse97]]: ...

    def Method98(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest98,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse98, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse98]]: ...

    def Method99(
        self,
        request: testproto.grpc.dummy_pb2.ManyRequest99,
        context: _ServicerContext,
    ) -> typing.Union[testproto.grpc.dummy_pb2.ManyResponse99, collections.abc.Awaitable[testproto.grpc.dummy_pb2.ManyResponse99]]: ...

def add_ManyRPCsServiceServicer_to_server(servicer: ManyRPCsServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
