# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testproto/test_extensions3.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'testproto/test_extensions3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from testproto import test3_pb2 as testproto_dot_test3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n testproto/test_extensions3.proto\x12\x05test3\x1a google/protobuf/descriptor.proto\x1a\x15testproto/test3.proto\"\x91\x01\n\x15MessageOptionsTestMsg:x\x92\x82\x19\x0cHello world!\x9a\x82\x19\x01\x41\x9a\x82\x19\x01\x42\x9a\x82\x19\x01\x43\xa0\x82\x19\x01\xaa\x82\x19\x02\x01\x02\xb2\x82\x19\x15\n\x13Hello OuterMessage3\xba\x82\x19\x17\n\x15Hello OuterMessage3 A\xba\x82\x19\x17\n\x15Hello OuterMessage3 B:=\n\x14test_field_extension\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\t:8\n\rscalar_option\x12\x1f.google.protobuf.MessageOptions\x18\xa2\x90\x03 \x01(\t:A\n\x16repeated_scalar_option\x12\x1f.google.protobuf.MessageOptions\x18\xa3\x90\x03 \x03(\t:H\n\x0b\x65num_option\x12\x1f.google.protobuf.MessageOptions\x18\xa4\x90\x03 \x01(\x0e\x32\x10.test3.OuterEnum:Q\n\x14repeated_enum_option\x12\x1f.google.protobuf.MessageOptions\x18\xa5\x90\x03 \x03(\x0e\x32\x10.test3.OuterEnum:K\n\nmsg_option\x12\x1f.google.protobuf.MessageOptions\x18\xa6\x90\x03 \x01(\x0b\x32\x14.test3.OuterMessage3:T\n\x13repeated_msg_option\x12\x1f.google.protobuf.MessageOptions\x18\xa7\x90\x03 \x03(\x0b\x32\x14.test3.OuterMessage3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testproto.test_extensions3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEOPTIONSTESTMSG']._loaded_options = None
  _globals['_MESSAGEOPTIONSTESTMSG']._serialized_options = b'\222\202\031\014Hello world!\232\202\031\001A\232\202\031\001B\232\202\031\001C\240\202\031\001\252\202\031\002\001\002\262\202\031\025\n\023Hello OuterMessage3\272\202\031\027\n\025Hello OuterMessage3 A\272\202\031\027\n\025Hello OuterMessage3 B'
  _globals['_MESSAGEOPTIONSTESTMSG']._serialized_start=101
  _globals['_MESSAGEOPTIONSTESTMSG']._serialized_end=246
# @@protoc_insertion_point(module_scope)
