"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.extension_dict
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FieldOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CASTTYPE_FIELD_NUMBER: builtins.int
    KEYTYPE_FIELD_NUMBER: builtins.int
    VALUETYPE_FIELD_NUMBER: builtins.int
    casttype: builtins.str
    """Tells mypy-protobuf to use a specific newtype rather than the normal type for this field."""
    keytype: builtins.str
    """Tells mypy-protobuf to use a specific type for keys; only makes sense on map fields"""
    valuetype: builtins.str
    """Tells mypy-protobuf to use a specific type for values; only makes sense on map fields"""
    def __init__(
        self,
        *,
        casttype: builtins.str = ...,
        keytype: builtins.str = ...,
        valuetype: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["casttype", b"casttype", "keytype", b"keytype", "valuetype", b"valuetype"]) -> None: ...

global___FieldOptions = FieldOptions

OPTIONS_FIELD_NUMBER: builtins.int
CASTTYPE_FIELD_NUMBER: builtins.int
KEYTYPE_FIELD_NUMBER: builtins.int
VALUETYPE_FIELD_NUMBER: builtins.int
options: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, global___FieldOptions]
"""Custom field options from mypy-protobuf"""
casttype: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.str]
"""Legacy fields. Prefer to use ones within `options` instead."""
keytype: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.str]
valuetype: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.str]
