"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers - Google's data interchange format
Copyright 2023 Google Inc.  All rights reserved.

Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file or at
https://developers.google.com/open-source/licenses/bsd
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InternalOptionsForce(google.protobuf.message.Message):
    """Internal options for testing only.
    These are used to turn on/off certain features that are not normally
    controlled from the .proto file, but we want to be able to control them for
    unit tests of said features.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Enum:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[InternalOptionsForce._Enum.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNSPECIFIED: InternalOptionsForce._Enum.ValueType  # 0
        FORCE_ON: InternalOptionsForce._Enum.ValueType  # 1
        FORCE_OFF: InternalOptionsForce._Enum.ValueType  # 2

    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper): ...
    UNSPECIFIED: InternalOptionsForce.Enum.ValueType  # 0
    FORCE_ON: InternalOptionsForce.Enum.ValueType  # 1
    FORCE_OFF: InternalOptionsForce.Enum.ValueType  # 2

    def __init__(
        self,
    ) -> None: ...

Global___InternalOptionsForce: typing_extensions.TypeAlias = InternalOptionsForce

@typing.final
class InternalFieldOptionsCpp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___InternalFieldOptionsCpp: typing_extensions.TypeAlias = InternalFieldOptionsCpp

@typing.final
class InternalFieldOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CPP_FIELD_NUMBER: builtins.int
    @property
    def cpp(self) -> Global___InternalFieldOptionsCpp: ...
    def __init__(
        self,
        *,
        cpp: Global___InternalFieldOptionsCpp | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["cpp", b"cpp"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["cpp", b"cpp"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InternalFieldOptions: typing_extensions.TypeAlias = InternalFieldOptions

INTERNAL_FIELD_OPTIONS_FIELD_NUMBER: builtins.int
internal_field_options: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, Global___InternalFieldOptions]
