"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import google.protobuf.descriptor as _google_protobuf_descriptor
import google.protobuf.message as _google_protobuf_message
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    import typing as _typing_extensions
else:
    import typing_extensions as _typing_extensions

DESCRIPTOR: _google_protobuf_descriptor.FileDescriptor

@_typing.final
class LateLoadedOptionUser(_google_protobuf_message.Message):
    DESCRIPTOR: _google_protobuf_descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___LateLoadedOptionUser: _typing_extensions.TypeAlias = LateLoadedOptionUser  # noqa: Y015
