"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
We don't put this in a package within proto2 because we need to make sure
that the generated code doesn't depend on being in the proto2 namespace.
In test_util.h we do "using namespace unittest = proto2_unittest".
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import unittest_lazy_dependencies_enum_pb2 as _unittest_lazy_dependencies_enum_pb2
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LazyMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    a: _builtins.int
    def __init__(
        self,
        *,
        a: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LazyMessage: _TypeAlias = LazyMessage  # noqa: Y015

LAZY_ENUM_OPTION_FIELD_NUMBER: _builtins.int
lazy_enum_option: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _unittest_lazy_dependencies_enum_pb2.LazyEnum.ValueType]
