"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
We don't put this in a package within proto2 because we need to make sure
that the generated code doesn't depend on being in the proto2 namespace.
In test_util.h we do "using namespace unittest = proto2_unittest".
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import unittest_lazy_dependencies_custom_option_pb2 as _unittest_lazy_dependencies_custom_option_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ImportedMessage(_message.Message):
    """The following are used to test that the proto file
    with the definition of the following field types is
    not built when this proto file is built. Then test
    that calling message_type() etc will build the correct
    descriptor lazily and return it.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LAZY_MESSAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def lazy_message(self) -> _unittest_lazy_dependencies_custom_option_pb2.LazyMessage: ...
    def __init__(
        self,
        *,
        lazy_message: _unittest_lazy_dependencies_custom_option_pb2.LazyMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lazy_message", b"lazy_message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lazy_message", b"lazy_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportedMessage: _TypeAlias = ImportedMessage  # noqa: Y015

@_typing.final
class MessageCustomOption(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MessageCustomOption: _TypeAlias = MessageCustomOption  # noqa: Y015

@_typing.final
class MessageCustomOption2(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MessageCustomOption2: _TypeAlias = MessageCustomOption2  # noqa: Y015
