"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers - Google's data interchange format
Copyright 2008 Google Inc.  All rights reserved.

Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file or at
https://developers.google.com/open-source/licenses/bsd
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _MyEnum:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MyEnumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MyEnum.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FOO: _MyEnum.ValueType  # 0
    BAR: _MyEnum.ValueType  # 1
    BAZ: _MyEnum.ValueType  # 2

class MyEnum(_MyEnum, metaclass=_MyEnumEnumTypeWrapper): ...

FOO: MyEnum.ValueType  # 0
BAR: MyEnum.ValueType  # 1
BAZ: MyEnum.ValueType  # 2
Global___MyEnum: _TypeAlias = MyEnum  # noqa: Y015

class _MyEnumPlusExtra:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MyEnumPlusExtraEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MyEnumPlusExtra.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    E_FOO: _MyEnumPlusExtra.ValueType  # 0
    E_BAR: _MyEnumPlusExtra.ValueType  # 1
    E_BAZ: _MyEnumPlusExtra.ValueType  # 2
    E_EXTRA: _MyEnumPlusExtra.ValueType  # 3

class MyEnumPlusExtra(_MyEnumPlusExtra, metaclass=_MyEnumPlusExtraEnumTypeWrapper): ...

E_FOO: MyEnumPlusExtra.ValueType  # 0
E_BAR: MyEnumPlusExtra.ValueType  # 1
E_BAZ: MyEnumPlusExtra.ValueType  # 2
E_EXTRA: MyEnumPlusExtra.ValueType  # 3
Global___MyEnumPlusExtra: _TypeAlias = MyEnumPlusExtra  # noqa: Y015

@_typing.final
class MyMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    E_FIELD_NUMBER: _builtins.int
    REPEATED_E_FIELD_NUMBER: _builtins.int
    REPEATED_PACKED_E_FIELD_NUMBER: _builtins.int
    REPEATED_PACKED_UNEXPECTED_E_FIELD_NUMBER: _builtins.int
    ONEOF_E_1_FIELD_NUMBER: _builtins.int
    ONEOF_E_2_FIELD_NUMBER: _builtins.int
    e: Global___MyEnum.ValueType
    oneof_e_1: Global___MyEnum.ValueType
    oneof_e_2: Global___MyEnum.ValueType
    @_builtins.property
    def repeated_e(self) -> _containers.RepeatedScalarFieldContainer[Global___MyEnum.ValueType]: ...
    @_builtins.property
    def repeated_packed_e(self) -> _containers.RepeatedScalarFieldContainer[Global___MyEnum.ValueType]: ...
    @_builtins.property
    def repeated_packed_unexpected_e(self) -> _containers.RepeatedScalarFieldContainer[Global___MyEnumPlusExtra.ValueType]:
        """not packed"""

    def __init__(
        self,
        *,
        e: Global___MyEnum.ValueType = ...,
        repeated_e: _abc.Iterable[Global___MyEnum.ValueType] = ...,
        repeated_packed_e: _abc.Iterable[Global___MyEnum.ValueType] = ...,
        repeated_packed_unexpected_e: _abc.Iterable[Global___MyEnumPlusExtra.ValueType] = ...,
        oneof_e_1: Global___MyEnum.ValueType = ...,
        oneof_e_2: Global___MyEnum.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["o", b"o", "oneof_e_1", b"oneof_e_1", "oneof_e_2", b"oneof_e_2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["e", b"e", "o", b"o", "oneof_e_1", b"oneof_e_1", "oneof_e_2", b"oneof_e_2", "repeated_e", b"repeated_e", "repeated_packed_e", b"repeated_packed_e", "repeated_packed_unexpected_e", b"repeated_packed_unexpected_e"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_o: _TypeAlias = _typing.Literal["oneof_e_1", "oneof_e_2"]  # noqa: Y015
    _WhichOneofArgType_o: _TypeAlias = _typing.Literal["o", b"o"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_o) -> _WhichOneofReturnType_o | None: ...

Global___MyMessage: _TypeAlias = MyMessage  # noqa: Y015

@_typing.final
class MyMessagePlusExtra(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    E_FIELD_NUMBER: _builtins.int
    REPEATED_E_FIELD_NUMBER: _builtins.int
    REPEATED_PACKED_E_FIELD_NUMBER: _builtins.int
    REPEATED_PACKED_UNEXPECTED_E_FIELD_NUMBER: _builtins.int
    ONEOF_E_1_FIELD_NUMBER: _builtins.int
    ONEOF_E_2_FIELD_NUMBER: _builtins.int
    e: Global___MyEnumPlusExtra.ValueType
    oneof_e_1: Global___MyEnumPlusExtra.ValueType
    oneof_e_2: Global___MyEnumPlusExtra.ValueType
    @_builtins.property
    def repeated_e(self) -> _containers.RepeatedScalarFieldContainer[Global___MyEnumPlusExtra.ValueType]: ...
    @_builtins.property
    def repeated_packed_e(self) -> _containers.RepeatedScalarFieldContainer[Global___MyEnumPlusExtra.ValueType]: ...
    @_builtins.property
    def repeated_packed_unexpected_e(self) -> _containers.RepeatedScalarFieldContainer[Global___MyEnumPlusExtra.ValueType]: ...
    def __init__(
        self,
        *,
        e: Global___MyEnumPlusExtra.ValueType = ...,
        repeated_e: _abc.Iterable[Global___MyEnumPlusExtra.ValueType] = ...,
        repeated_packed_e: _abc.Iterable[Global___MyEnumPlusExtra.ValueType] = ...,
        repeated_packed_unexpected_e: _abc.Iterable[Global___MyEnumPlusExtra.ValueType] = ...,
        oneof_e_1: Global___MyEnumPlusExtra.ValueType = ...,
        oneof_e_2: Global___MyEnumPlusExtra.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["o", b"o", "oneof_e_1", b"oneof_e_1", "oneof_e_2", b"oneof_e_2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["e", b"e", "o", b"o", "oneof_e_1", b"oneof_e_1", "oneof_e_2", b"oneof_e_2", "repeated_e", b"repeated_e", "repeated_packed_e", b"repeated_packed_e", "repeated_packed_unexpected_e", b"repeated_packed_unexpected_e"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_o: _TypeAlias = _typing.Literal["oneof_e_1", "oneof_e_2"]  # noqa: Y015
    _WhichOneofArgType_o: _TypeAlias = _typing.Literal["o", b"o"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_o) -> _WhichOneofReturnType_o | None: ...

Global___MyMessagePlusExtra: _TypeAlias = MyMessagePlusExtra  # noqa: Y015
