"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import unittest_delimited_import_pb2 as _unittest_delimited_import_pb2
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LengthPrefixed(_message.Message):
    """Test various scenarios that are now possible in edition 2023+ that weren't in
    google.protobuf.
    """

    DESCRIPTOR: _descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    a: _builtins.int
    b: _builtins.int
    def __init__(
        self,
        *,
        a: _builtins.int | None = ...,
        b: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LengthPrefixed: _TypeAlias = LengthPrefixed  # noqa: Y015

@_typing.final
class NotGroupLikeScope(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    a: _builtins.int
    b: _builtins.int
    def __init__(
        self,
        *,
        a: _builtins.int | None = ...,
        b: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NotGroupLikeScope: _TypeAlias = NotGroupLikeScope  # noqa: Y015

@_typing.final
class GroupLikeFileScope(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    a: _builtins.int
    b: _builtins.int
    def __init__(
        self,
        *,
        a: _builtins.int | None = ...,
        b: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GroupLikeFileScope: _TypeAlias = GroupLikeFileScope  # noqa: Y015

@_typing.final
class TestDelimited(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class LengthPrefixed(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        A_FIELD_NUMBER: _builtins.int
        B_FIELD_NUMBER: _builtins.int
        a: _builtins.int
        b: _builtins.int
        def __init__(
            self,
            *,
            a: _builtins.int | None = ...,
            b: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GroupLike(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        A_FIELD_NUMBER: _builtins.int
        B_FIELD_NUMBER: _builtins.int
        a: _builtins.int
        b: _builtins.int
        def __init__(
            self,
            *,
            a: _builtins.int | None = ...,
            b: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    LENGTHPREFIXED_FIELD_NUMBER: _builtins.int
    NESTED_FIELD_NUMBER: _builtins.int
    GROUPLIKE_FIELD_NUMBER: _builtins.int
    NOTGROUPLIKE_FIELD_NUMBER: _builtins.int
    NOTGROUPLIKESCOPE_FIELD_NUMBER: _builtins.int
    MESSAGEIMPORT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def lengthprefixed(self) -> Global___TestDelimited.LengthPrefixed:
        """Non-delimited field that otherwise looks group-like."""

    @_builtins.property
    def nested(self) -> Global___TestDelimited:
        """Nested field for nested tests."""

    @_builtins.property
    def grouplike(self) -> Global___TestDelimited.GroupLike:
        """Truly group-like field."""

    @_builtins.property
    def notgrouplike(self) -> Global___TestDelimited.GroupLike:
        """Delimited field that isn't group-like solely because of its name."""

    @_builtins.property
    def notgrouplikescope(self) -> Global___NotGroupLikeScope:
        """Delimited field that isn't group-like because of the scope of its type."""

    @_builtins.property
    def messageimport(self) -> _unittest_delimited_import_pb2.MessageImport:
        """Delimited field that's grouplike except that it's an imported type."""

    def __init__(
        self,
        *,
        lengthprefixed: Global___TestDelimited.LengthPrefixed | None = ...,
        nested: Global___TestDelimited | None = ...,
        grouplike: Global___TestDelimited.GroupLike | None = ...,
        notgrouplike: Global___TestDelimited.GroupLike | None = ...,
        notgrouplikescope: Global___NotGroupLikeScope | None = ...,
        messageimport: _unittest_delimited_import_pb2.MessageImport | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["grouplike", b"grouplike", "lengthprefixed", b"lengthprefixed", "messageimport", b"messageimport", "nested", b"nested", "notgrouplike", b"notgrouplike", "notgrouplikescope", b"notgrouplikescope"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["grouplike", b"grouplike", "lengthprefixed", b"lengthprefixed", "messageimport", b"messageimport", "nested", b"nested", "notgrouplike", b"notgrouplike", "notgrouplikescope", b"notgrouplikescope"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TestDelimited: _TypeAlias = TestDelimited  # noqa: Y015

LENGTHPREFIXED_FIELD_NUMBER: _builtins.int
GROUPLIKEFILESCOPE_FIELD_NUMBER: _builtins.int
NOT_GROUP_LIKE_SCOPE_FIELD_NUMBER: _builtins.int
GROUPLIKE_FIELD_NUMBER: _builtins.int
MESSAGEIMPORT_FIELD_NUMBER: _builtins.int
lengthprefixed: _extension_dict._ExtensionFieldDescriptor[Global___TestDelimited, Global___LengthPrefixed]
"""Non-delimited field that otherwise looks group-like."""
grouplikefilescope: _extension_dict._ExtensionFieldDescriptor[Global___TestDelimited, Global___GroupLikeFileScope]
"""Truly group-like extension."""
not_group_like_scope: _extension_dict._ExtensionFieldDescriptor[Global___TestDelimited, Global___NotGroupLikeScope]
"""Delimited extension that isn't group-like because of its name."""
grouplike: _extension_dict._ExtensionFieldDescriptor[Global___TestDelimited, Global___TestDelimited.GroupLike]
"""Delimited extension that isn't group-like because of the scope of its type."""
messageimport: _extension_dict._ExtensionFieldDescriptor[Global___TestDelimited, _unittest_delimited_import_pb2.MessageImport]
"""Delimited extension that's grouplike except that it's an imported type."""
