"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import google.protobuf.descriptor as _google_protobuf_descriptor
import google.protobuf.message as _google_protobuf_message
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    import typing as _typing_extensions
else:
    import typing_extensions as _typing_extensions

DESCRIPTOR: _google_protobuf_descriptor.FileDescriptor

@_typing.final
class MessageImport(_google_protobuf_message.Message):
    DESCRIPTOR: _google_protobuf_descriptor.Descriptor

    A_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    a: _builtins.int
    b: _builtins.int
    def __init__(
        self,
        *,
        a: _builtins.int | None = ...,
        b: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _typing_extensions.TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _typing_extensions.TypeAlias = _typing.Literal["a", b"a", "b", b"b"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MessageImport: _typing_extensions.TypeAlias = MessageImport  # noqa: Y015
