"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class NoPackage(_message.Message):
    """Intentionally don't set a package - just to make sure we can handle it."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___NoPackage: _TypeAlias = NoPackage  # noqa: Y015

@_typing.final
class NoPackage2(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NP_FIELD_NUMBER: _builtins.int
    NP_REP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def np(self) -> Global___NoPackage: ...
    @_builtins.property
    def np_rep(self) -> _containers.RepeatedCompositeFieldContainer[Global___NoPackage]: ...
    def __init__(
        self,
        *,
        np: Global___NoPackage | None = ...,
        np_rep: _abc.Iterable[Global___NoPackage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["np", b"np"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["np", b"np", "np_rep", b"np_rep"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NoPackage2: _TypeAlias = NoPackage2  # noqa: Y015
